inherit_from: .rubocop_todo.yml

AllCops:
  Exclude:
    - DerivedData/**/*
    - Pods/**/*
    - vendor/**/*
  NewCops: enable
  SuggestExtensions:
    rubocop-rake: false

Layout/LineLength:
  Max: 180
  Exclude:
    - fastlane/Fastfile

Metrics/BlockLength:
  Exclude:
    - fastlane/Fastfile
    - scripts/themes/generate_themes.rb

Metrics/MethodLength:
  Max: 30
  Exclude:
    - fastlane/Fastfile
    - scripts/themes/generate_themes.rb

Naming/AsciiIdentifiers:
  Exclude:
    - scripts/themes/generate_themes.rb
