AllCops:
  Exclude:
    - DerivedData/**/*
    - Pods/**/*
    - vendor/**/*
  NewCops: enable
  SuggestExtensions:
    # For some reason, RuboCop suggests installing this, even though we don't use Rake
    rubocop-rake: false

Layout/LineLength:
  Exclude:
    - 'scripts/themes/generate_themes.rb'

Metrics/AbcSize:
  Exclude:
    - 'scripts/themes/generate_themes.rb'

Metrics/BlockLength:
  Exclude:
    - fastlane/*file
    - 'scripts/themes/generate_themes.rb'

Metrics/BlockNesting:
  Exclude:
    - fastlane/*file
    - 'scripts/themes/generate_themes.rb'

Metrics/CyclomaticComplexity:
  Exclude:
    - 'scripts/themes/generate_themes.rb'

Metrics/MethodLength:
  Exclude:
    - 'scripts/themes/generate_themes.rb'

Metrics/PerceivedComplexity:
  Exclude:
    - 'scripts/themes/generate_themes.rb'

Naming/AsciiIdentifiers:
  Exclude:
    # Uses rosé in code generation. If we decide to address this, it should be
    # in a dedicated commit that updates the consuming Swift code, too.
    - 'scripts/themes/generate_themes.rb'

Naming/FileName:
  Exclude:
    - fastlane/*file
    - '**/*.podspec'

Style/Documentation:
  Exclude:
    - 'scripts/themes/generate_themes.rb'
