// This file was autogenerated by some hot garbage in the `uniffi` crate.
// Trust me, you don't want to mess with it!

// swiftlint:disable all
import Foundation

// Depending on the consumer's build setup, the low-level FFI code
// might be in a separate module, or it might be compiled inline into
// this module. This is a bit of light hackery to work with both.
#if canImport(FingerprintFFI)
    import FingerprintFFI
#endif

private extension RustBuffer {
    /// Allocate a new buffer, copying the contents of a `UInt8` array.
    init(bytes: [UInt8]) {
        let rbuf = bytes.withUnsafeBufferPointer { ptr in
            RustBuffer.from(ptr)
        }
        self.init(capacity: rbuf.capacity, len: rbuf.len, data: rbuf.data)
    }

    static func empty() -> RustBuffer {
        RustBuffer(capacity: 0, len: 0, data: nil)
    }

    static func from(_ ptr: UnsafeBufferPointer<UInt8>) -> RustBuffer {
        try! rustCall { ffi_fingerprint_uniffi_rustbuffer_from_bytes(ForeignBytes(bufferPointer: ptr), $0) }
    }

    /// Frees the buffer in place.
    /// The buffer must not be used after this is called.
    func deallocate() {
        try! rustCall { ffi_fingerprint_uniffi_rustbuffer_free(self, $0) }
    }
}

private extension ForeignBytes {
    init(bufferPointer: UnsafeBufferPointer<UInt8>) {
        self.init(len: Int32(bufferPointer.count), data: bufferPointer.baseAddress)
    }
}

// For every type used in the interface, we provide helper methods for conveniently
// lifting and lowering that type from C-compatible data, and for reading and writing
// values of that type in a buffer.

// Helper classes/extensions that don't change.
// Someday, this will be in a library of its own.

private extension Data {
    init(rustBuffer: RustBuffer) {
        self.init(
            bytesNoCopy: rustBuffer.data!,
            count: Int(rustBuffer.len),
            deallocator: .none
        )
    }
}

// Define reader functionality.  Normally this would be defined in a class or
// struct, but we use standalone functions instead in order to make external
// types work.
//
// With external types, one swift source file needs to be able to call the read
// method on another source file's FfiConverter, but then what visibility
// should Reader have?
// - If Reader is fileprivate, then this means the read() must also
//   be fileprivate, which doesn't work with external types.
// - If Reader is internal/public, we'll get compile errors since both source
//   files will try define the same type.
//
// Instead, the read() method and these helper functions input a tuple of data

private func createReader(data: Data) -> (data: Data, offset: Data.Index) {
    (data: data, offset: 0)
}

/// Reads an integer at the current offset, in big-endian order, and advances
/// the offset on success. Throws if reading the integer would move the
/// offset past the end of the buffer.
private func readInt<T: FixedWidthInteger>(_ reader: inout (data: Data, offset: Data.Index)) throws -> T {
    let range = reader.offset ..< reader.offset + MemoryLayout<T>.size
    guard reader.data.count >= range.upperBound else {
        throw UniffiInternalError.bufferOverflow
    }
    if T.self == UInt8.self {
        let value = reader.data[reader.offset]
        reader.offset += 1
        return value as! T
    }
    var value: T = 0
    let _ = withUnsafeMutableBytes(of: &value) { reader.data.copyBytes(to: $0, from: range) }
    reader.offset = range.upperBound
    return value.bigEndian
}

/// Reads an arbitrary number of bytes, to be used to read
/// raw bytes, this is useful when lifting strings
private func readBytes(_ reader: inout (data: Data, offset: Data.Index), count: Int) throws -> [UInt8] {
    let range = reader.offset ..< (reader.offset + count)
    guard reader.data.count >= range.upperBound else {
        throw UniffiInternalError.bufferOverflow
    }
    var value = [UInt8](repeating: 0, count: count)
    value.withUnsafeMutableBufferPointer { buffer in
        reader.data.copyBytes(to: buffer, from: range)
    }
    reader.offset = range.upperBound
    return value
}

/// Reads a float at the current offset.
private func readFloat(_ reader: inout (data: Data, offset: Data.Index)) throws -> Float {
    return try Float(bitPattern: readInt(&reader))
}

/// Reads a float at the current offset.
private func readDouble(_ reader: inout (data: Data, offset: Data.Index)) throws -> Double {
    return try Double(bitPattern: readInt(&reader))
}

/// Indicates if the offset has reached the end of the buffer.
private func hasRemaining(_ reader: (data: Data, offset: Data.Index)) -> Bool {
    return reader.offset < reader.data.count
}

// Define writer functionality.  Normally this would be defined in a class or
// struct, but we use standalone functions instead in order to make external
// types work.  See the above discussion on Readers for details.

private func createWriter() -> [UInt8] {
    return []
}

private func writeBytes<S: Sequence>(_ writer: inout [UInt8], _ byteArr: S) where S.Element == UInt8 {
    writer.append(contentsOf: byteArr)
}

/// Writes an integer in big-endian order.
///
/// Warning: make sure what you are trying to write
/// is in the correct type!
private func writeInt<T: FixedWidthInteger>(_ writer: inout [UInt8], _ value: T) {
    var value = value.bigEndian
    withUnsafeBytes(of: &value) { writer.append(contentsOf: $0) }
}

private func writeFloat(_ writer: inout [UInt8], _ value: Float) {
    writeInt(&writer, value.bitPattern)
}

private func writeDouble(_ writer: inout [UInt8], _ value: Double) {
    writeInt(&writer, value.bitPattern)
}

/// Protocol for types that transfer other types across the FFI. This is
/// analogous to the Rust trait of the same name.
private protocol FfiConverter {
    associatedtype FfiType
    associatedtype SwiftType

    static func lift(_ value: FfiType) throws -> SwiftType
    static func lower(_ value: SwiftType) -> FfiType
    static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType
    static func write(_ value: SwiftType, into buf: inout [UInt8])
}

/// Types conforming to `Primitive` pass themselves directly over the FFI.
private protocol FfiConverterPrimitive: FfiConverter where FfiType == SwiftType {}

extension FfiConverterPrimitive {
    #if swift(>=5.8)
        @_documentation(visibility: private)
    #endif
    public static func lift(_ value: FfiType) throws -> SwiftType {
        return value
    }

    #if swift(>=5.8)
        @_documentation(visibility: private)
    #endif
    public static func lower(_ value: SwiftType) -> FfiType {
        return value
    }
}

/// Types conforming to `FfiConverterRustBuffer` lift and lower into a `RustBuffer`.
/// Used for complex types where it's hard to write a custom lift/lower.
private protocol FfiConverterRustBuffer: FfiConverter where FfiType == RustBuffer {}

extension FfiConverterRustBuffer {
    #if swift(>=5.8)
        @_documentation(visibility: private)
    #endif
    public static func lift(_ buf: RustBuffer) throws -> SwiftType {
        var reader = createReader(data: Data(rustBuffer: buf))
        let value = try read(from: &reader)
        if hasRemaining(reader) {
            throw UniffiInternalError.incompleteData
        }
        buf.deallocate()
        return value
    }

    #if swift(>=5.8)
        @_documentation(visibility: private)
    #endif
    public static func lower(_ value: SwiftType) -> RustBuffer {
        var writer = createWriter()
        write(value, into: &writer)
        return RustBuffer(bytes: writer)
    }
}

/// An error type for FFI errors. These errors occur at the UniFFI level, not
/// the library level.
private enum UniffiInternalError: LocalizedError {
    case bufferOverflow
    case incompleteData
    case unexpectedOptionalTag
    case unexpectedEnumCase
    case unexpectedNullPointer
    case unexpectedRustCallStatusCode
    case unexpectedRustCallError
    case unexpectedStaleHandle
    case rustPanic(_ message: String)

    var errorDescription: String? {
        switch self {
        case .bufferOverflow: return "Reading the requested value would read past the end of the buffer"
        case .incompleteData: return "The buffer still has data after lifting its containing value"
        case .unexpectedOptionalTag: return "Unexpected optional tag; should be 0 or 1"
        case .unexpectedEnumCase: return "Raw enum value doesn't match any cases"
        case .unexpectedNullPointer: return "Raw pointer value was null"
        case .unexpectedRustCallStatusCode: return "Unexpected RustCallStatus code"
        case .unexpectedRustCallError: return "CALL_ERROR but no errorClass specified"
        case .unexpectedStaleHandle: return "The object in the handle map has been dropped already"
        case let .rustPanic(message): return message
        }
    }
}

private extension NSLock {
    func withLock<T>(f: () throws -> T) rethrows -> T {
        lock()
        defer { self.unlock() }
        return try f()
    }
}

private let CALL_SUCCESS: Int8 = 0
private let CALL_ERROR: Int8 = 1
private let CALL_UNEXPECTED_ERROR: Int8 = 2
private let CALL_CANCELLED: Int8 = 3

private extension RustCallStatus {
    init() {
        self.init(
            code: CALL_SUCCESS,
            errorBuf: RustBuffer(
                capacity: 0,
                len: 0,
                data: nil
            )
        )
    }
}

private func rustCall<T>(_ callback: (UnsafeMutablePointer<RustCallStatus>) -> T) throws -> T {
    let neverThrow: ((RustBuffer) throws -> Never)? = nil
    return try makeRustCall(callback, errorHandler: neverThrow)
}

private func rustCallWithError<T, E: Swift.Error>(
    _ errorHandler: @escaping (RustBuffer) throws -> E,
    _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T
) throws -> T {
    try makeRustCall(callback, errorHandler: errorHandler)
}

private func makeRustCall<T, E: Swift.Error>(
    _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T,
    errorHandler: ((RustBuffer) throws -> E)?
) throws -> T {
    uniffiEnsureInitialized()
    var callStatus = RustCallStatus()
    let returnedVal = callback(&callStatus)
    try uniffiCheckCallStatus(callStatus: callStatus, errorHandler: errorHandler)
    return returnedVal
}

private func uniffiCheckCallStatus<E: Swift.Error>(
    callStatus: RustCallStatus,
    errorHandler: ((RustBuffer) throws -> E)?
) throws {
    switch callStatus.code {
    case CALL_SUCCESS:
        return

    case CALL_ERROR:
        if let errorHandler = errorHandler {
            throw try errorHandler(callStatus.errorBuf)
        } else {
            callStatus.errorBuf.deallocate()
            throw UniffiInternalError.unexpectedRustCallError
        }

    case CALL_UNEXPECTED_ERROR:
        // When the rust code sees a panic, it tries to construct a RustBuffer
        // with the message.  But if that code panics, then it just sends back
        // an empty buffer.
        if callStatus.errorBuf.len > 0 {
            throw try UniffiInternalError.rustPanic(FfiConverterString.lift(callStatus.errorBuf))
        } else {
            callStatus.errorBuf.deallocate()
            throw UniffiInternalError.rustPanic("Rust panic")
        }

    case CALL_CANCELLED:
        fatalError("Cancellation not supported yet")

    default:
        throw UniffiInternalError.unexpectedRustCallStatusCode
    }
}

private func uniffiTraitInterfaceCall<T>(
    callStatus: UnsafeMutablePointer<RustCallStatus>,
    makeCall: () throws -> T,
    writeReturn: (T) -> Void
) {
    do {
        try writeReturn(makeCall())
    } catch {
        callStatus.pointee.code = CALL_UNEXPECTED_ERROR
        callStatus.pointee.errorBuf = FfiConverterString.lower(String(describing: error))
    }
}

private func uniffiTraitInterfaceCallWithError<T, E>(
    callStatus: UnsafeMutablePointer<RustCallStatus>,
    makeCall: () throws -> T,
    writeReturn: (T) -> Void,
    lowerError: (E) -> RustBuffer
) {
    do {
        try writeReturn(makeCall())
    } catch let error as E {
        callStatus.pointee.code = CALL_ERROR
        callStatus.pointee.errorBuf = lowerError(error)
    } catch {
        callStatus.pointee.code = CALL_UNEXPECTED_ERROR
        callStatus.pointee.errorBuf = FfiConverterString.lower(String(describing: error))
    }
}

private class UniffiHandleMap<T> {
    private var map: [UInt64: T] = [:]
    private let lock = NSLock()
    private var currentHandle: UInt64 = 1

    func insert(obj: T) -> UInt64 {
        lock.withLock {
            let handle = currentHandle
            currentHandle += 1
            map[handle] = obj
            return handle
        }
    }

    func get(handle: UInt64) throws -> T {
        try lock.withLock {
            guard let obj = map[handle] else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return obj
        }
    }

    @discardableResult
    func remove(handle: UInt64) throws -> T {
        try lock.withLock {
            guard let obj = map.removeValue(forKey: handle) else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return obj
        }
    }

    var count: Int {
        map.count
    }
}

// Public interface members begin here.

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
private struct FfiConverterUInt16: FfiConverterPrimitive {
    typealias FfiType = UInt16
    typealias SwiftType = UInt16

    static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> UInt16 {
        return try lift(readInt(&buf))
    }

    static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
private struct FfiConverterInt16: FfiConverterPrimitive {
    typealias FfiType = Int16
    typealias SwiftType = Int16

    static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Int16 {
        return try lift(readInt(&buf))
    }

    static func write(_ value: Int16, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
private struct FfiConverterUInt32: FfiConverterPrimitive {
    typealias FfiType = UInt32
    typealias SwiftType = UInt32

    static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> UInt32 {
        return try lift(readInt(&buf))
    }

    static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
private struct FfiConverterFloat: FfiConverterPrimitive {
    typealias FfiType = Float
    typealias SwiftType = Float

    static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Float {
        return try lift(readFloat(&buf))
    }

    static func write(_ value: Float, into buf: inout [UInt8]) {
        writeFloat(&buf, lower(value))
    }
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
private struct FfiConverterString: FfiConverter {
    typealias SwiftType = String
    typealias FfiType = RustBuffer

    static func lift(_ value: RustBuffer) throws -> String {
        defer {
            value.deallocate()
        }
        if value.data == nil {
            return String()
        }
        let bytes = UnsafeBufferPointer<UInt8>(start: value.data!, count: Int(value.len))
        return String(bytes: bytes, encoding: String.Encoding.utf8)!
    }

    static func lower(_ value: String) -> RustBuffer {
        return value.utf8CString.withUnsafeBufferPointer { ptr in
            // The swift string gives us int8_t, we want uint8_t.
            ptr.withMemoryRebound(to: UInt8.self) { ptr in
                // The swift string gives us a trailing null byte, we don't want it.
                let buf = UnsafeBufferPointer(rebasing: ptr.prefix(upTo: ptr.count - 1))
                return RustBuffer.from(buf)
            }
        }
    }

    static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> String {
        let len: Int32 = try readInt(&buf)
        return try String(bytes: readBytes(&buf, count: Int(len)), encoding: String.Encoding.utf8)!
    }

    static func write(_ value: String, into buf: inout [UInt8]) {
        let len = Int32(value.utf8.count)
        writeInt(&buf, len)
        writeBytes(&buf, value.utf8)
    }
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
private struct FfiConverterData: FfiConverterRustBuffer {
    typealias SwiftType = Data

    static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Data {
        let len: Int32 = try readInt(&buf)
        return try Data(readBytes(&buf, count: Int(len)))
    }

    static func write(_ value: Data, into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        writeBytes(&buf, value)
    }
}

/**
 * Matcher for comparing windowed fingerprint checkpoints.
 *
 * This is designed for matching audio with different ad insertions or timing offsets.
 */
public protocol CheckpointMatcherProtocol: AnyObject {
    /**
     * Add a checkpoint to the matcher.
     *
     * # Arguments
     * * `timestamp` - Timestamp in seconds.
     * * `hashes` - Fingerprint hash values.
     * * `duration` - Duration of the fingerprinted segment in seconds.
     */
    func add(timestamp: Float, hashes: [UInt32], duration: Float)

    /**
     * Clear all checkpoints from the matcher.
     */
    func clear()

    /**
     * Get the number of checkpoints in the matcher.
     */
    func count() -> UInt32

    /**
     * Find the top N matching checkpoints for a query fingerprint.
     *
     * # Arguments
     * * `query_hashes` - Query fingerprint hash values.
     * * `max_results` - Maximum number of results to return.
     *
     * # Returns
     * Vector of matches sorted by score (highest first).
     */
    func findTopMatches(queryHashes: [UInt32], maxResults: UInt32) -> [MatchResult]

    /**
     * Set the maximum drift for comparisons.
     */
    func setDrift(maxDrift: UInt32)
}

/**
 * Matcher for comparing windowed fingerprint checkpoints.
 *
 * This is designed for matching audio with different ad insertions or timing offsets.
 */
open class CheckpointMatcher:
    CheckpointMatcherProtocol
{
    fileprivate let pointer: UnsafeMutableRawPointer!

    // Used to instantiate a [FFIObject] without an actual pointer, for fakes in tests, mostly.
    #if swift(>=5.8)
        @_documentation(visibility: private)
    #endif
    public struct NoPointer {
        public init() {}
    }

    // TODO: We'd like this to be `private` but for Swifty reasons,
    // we can't implement `FfiConverter` without making this `required` and we can't
    // make it `required` without making it `public`.
    public required init(unsafeFromRawPointer pointer: UnsafeMutableRawPointer) {
        self.pointer = pointer
    }

    // This constructor can be used to instantiate a fake object.
    // - Parameter noPointer: Placeholder value so we can have a constructor separate from the default empty one that may be implemented for classes extending [FFIObject].
    //
    // - Warning:
    //     Any object instantiated with this constructor cannot be passed to an actual Rust-backed object. Since there isn't a backing [Pointer] the FFI lower functions will crash.
    #if swift(>=5.8)
        @_documentation(visibility: private)
    #endif
    public init(noPointer _: NoPointer) {
        pointer = nil
    }

    #if swift(>=5.8)
        @_documentation(visibility: private)
    #endif
    public func uniffiClonePointer() -> UnsafeMutableRawPointer {
        return try! rustCall { uniffi_fingerprint_uniffi_fn_clone_checkpointmatcher(self.pointer, $0) }
    }

    /**
     * Create a new checkpoint matcher with default drift.
     */
    public convenience init() {
        let pointer =
            try! rustCall {
                uniffi_fingerprint_uniffi_fn_constructor_checkpointmatcher_new($0)
            }
        self.init(unsafeFromRawPointer: pointer)
    }

    deinit {
        guard let pointer = pointer else {
            return
        }

        try! rustCall { uniffi_fingerprint_uniffi_fn_free_checkpointmatcher(pointer, $0) }
    }

    /**
     * Create a matcher with a specific drift tolerance.
     */
    public static func withDrift(maxDrift: UInt32) -> CheckpointMatcher {
        return try! FfiConverterTypeCheckpointMatcher.lift(try! rustCall {
            uniffi_fingerprint_uniffi_fn_constructor_checkpointmatcher_with_drift(
                FfiConverterUInt32.lower(maxDrift), $0
            )
        })
    }

    /**
     * Add a checkpoint to the matcher.
     *
     * # Arguments
     * * `timestamp` - Timestamp in seconds.
     * * `hashes` - Fingerprint hash values.
     * * `duration` - Duration of the fingerprinted segment in seconds.
     */
    open func add(timestamp: Float, hashes: [UInt32], duration: Float) {
        try! rustCall {
            uniffi_fingerprint_uniffi_fn_method_checkpointmatcher_add(self.uniffiClonePointer(),
                                                                      FfiConverterFloat.lower(timestamp),
                                                                      FfiConverterSequenceUInt32.lower(hashes),
                                                                      FfiConverterFloat.lower(duration), $0)
        }
    }

    /**
     * Clear all checkpoints from the matcher.
     */
    open func clear() {
        try! rustCall {
            uniffi_fingerprint_uniffi_fn_method_checkpointmatcher_clear(self.uniffiClonePointer(), $0)
        }
    }

    /**
     * Get the number of checkpoints in the matcher.
     */
    open func count() -> UInt32 {
        return try! FfiConverterUInt32.lift(try! rustCall {
            uniffi_fingerprint_uniffi_fn_method_checkpointmatcher_count(self.uniffiClonePointer(), $0)
        })
    }

    /**
     * Find the top N matching checkpoints for a query fingerprint.
     *
     * # Arguments
     * * `query_hashes` - Query fingerprint hash values.
     * * `max_results` - Maximum number of results to return.
     *
     * # Returns
     * Vector of matches sorted by score (highest first).
     */
    open func findTopMatches(queryHashes: [UInt32], maxResults: UInt32) -> [MatchResult] {
        return try! FfiConverterSequenceTypeMatchResult.lift(try! rustCall {
            uniffi_fingerprint_uniffi_fn_method_checkpointmatcher_find_top_matches(self.uniffiClonePointer(),
                                                                                   FfiConverterSequenceUInt32.lower(queryHashes),
                                                                                   FfiConverterUInt32.lower(maxResults), $0)
        })
    }

    /**
     * Set the maximum drift for comparisons.
     */
    open func setDrift(maxDrift: UInt32) {
        try! rustCall {
            uniffi_fingerprint_uniffi_fn_method_checkpointmatcher_set_drift(self.uniffiClonePointer(),
                                                                            FfiConverterUInt32.lower(maxDrift), $0)
        }
    }
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
public struct FfiConverterTypeCheckpointMatcher: FfiConverter {
    typealias FfiType = UnsafeMutableRawPointer
    typealias SwiftType = CheckpointMatcher

    public static func lift(_ pointer: UnsafeMutableRawPointer) throws -> CheckpointMatcher {
        return CheckpointMatcher(unsafeFromRawPointer: pointer)
    }

    public static func lower(_ value: CheckpointMatcher) -> UnsafeMutableRawPointer {
        return value.uniffiClonePointer()
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> CheckpointMatcher {
        let v: UInt64 = try readInt(&buf)
        // The Rust code won't compile if a pointer won't fit in a UInt64.
        // We have to go via `UInt` because that's the thing that's the size of a pointer.
        let ptr = UnsafeMutableRawPointer(bitPattern: UInt(truncatingIfNeeded: v))
        if ptr == nil {
            throw UniffiInternalError.unexpectedNullPointer
        }
        return try lift(ptr!)
    }

    public static func write(_ value: CheckpointMatcher, into buf: inout [UInt8]) {
        // This fiddling is because `Int` is the thing that's the same size as a pointer.
        // The Rust code won't compile if a pointer won't fit in a `UInt64`.
        writeInt(&buf, UInt64(bitPattern: Int64(Int(bitPattern: lower(value)))))
    }
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
public func FfiConverterTypeCheckpointMatcher_lift(_ pointer: UnsafeMutableRawPointer) throws -> CheckpointMatcher {
    return try FfiConverterTypeCheckpointMatcher.lift(pointer)
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
public func FfiConverterTypeCheckpointMatcher_lower(_ value: CheckpointMatcher) -> UnsafeMutableRawPointer {
    return FfiConverterTypeCheckpointMatcher.lower(value)
}

/**
 * Audio fingerprinter for generating fingerprints from audio data.
 */
public protocol FingerprinterProtocol: AnyObject {
    /**
     * Generate windowed fingerprints from raw audio data.
     *
     * # Arguments
     * * `data` - Raw audio file data (WAV or MP3 format).
     * * `window_duration_ms` - Duration of each window in milliseconds.
     * * `window_interval_ms` - Interval between windows in milliseconds.
     *
     * # Returns
     * Array of WindowedFingerprint, or error if generation failed.
     */
    func fingerprintDataWindowed(data: Data, windowDurationMs: UInt32, windowIntervalMs: UInt32) throws -> [WindowedFingerprint]
}

/**
 * Audio fingerprinter for generating fingerprints from audio data.
 */
open class Fingerprinter:
    FingerprinterProtocol
{
    fileprivate let pointer: UnsafeMutableRawPointer!

    // Used to instantiate a [FFIObject] without an actual pointer, for fakes in tests, mostly.
    #if swift(>=5.8)
        @_documentation(visibility: private)
    #endif
    public struct NoPointer {
        public init() {}
    }

    // TODO: We'd like this to be `private` but for Swifty reasons,
    // we can't implement `FfiConverter` without making this `required` and we can't
    // make it `required` without making it `public`.
    public required init(unsafeFromRawPointer pointer: UnsafeMutableRawPointer) {
        self.pointer = pointer
    }

    // This constructor can be used to instantiate a fake object.
    // - Parameter noPointer: Placeholder value so we can have a constructor separate from the default empty one that may be implemented for classes extending [FFIObject].
    //
    // - Warning:
    //     Any object instantiated with this constructor cannot be passed to an actual Rust-backed object. Since there isn't a backing [Pointer] the FFI lower functions will crash.
    #if swift(>=5.8)
        @_documentation(visibility: private)
    #endif
    public init(noPointer _: NoPointer) {
        pointer = nil
    }

    #if swift(>=5.8)
        @_documentation(visibility: private)
    #endif
    public func uniffiClonePointer() -> UnsafeMutableRawPointer {
        return try! rustCall { uniffi_fingerprint_uniffi_fn_clone_fingerprinter(self.pointer, $0) }
    }

    /**
     * Create a new Fingerprinter with default settings.
     */
    public convenience init() {
        let pointer =
            try! rustCall {
                uniffi_fingerprint_uniffi_fn_constructor_fingerprinter_new($0)
            }
        self.init(unsafeFromRawPointer: pointer)
    }

    deinit {
        guard let pointer = pointer else {
            return
        }

        try! rustCall { uniffi_fingerprint_uniffi_fn_free_fingerprinter(pointer, $0) }
    }

    /**
     * Generate windowed fingerprints from raw audio data.
     *
     * # Arguments
     * * `data` - Raw audio file data (WAV or MP3 format).
     * * `window_duration_ms` - Duration of each window in milliseconds.
     * * `window_interval_ms` - Interval between windows in milliseconds.
     *
     * # Returns
     * Array of WindowedFingerprint, or error if generation failed.
     */
    open func fingerprintDataWindowed(data: Data, windowDurationMs: UInt32, windowIntervalMs: UInt32) throws -> [WindowedFingerprint] {
        return try FfiConverterSequenceTypeWindowedFingerprint.lift(rustCallWithError(FfiConverterTypeFingerprintError.lift) {
            uniffi_fingerprint_uniffi_fn_method_fingerprinter_fingerprint_data_windowed(self.uniffiClonePointer(),
                                                                                        FfiConverterData.lower(data),
                                                                                        FfiConverterUInt32.lower(windowDurationMs),
                                                                                        FfiConverterUInt32.lower(windowIntervalMs), $0)
        })
    }
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
public struct FfiConverterTypeFingerprinter: FfiConverter {
    typealias FfiType = UnsafeMutableRawPointer
    typealias SwiftType = Fingerprinter

    public static func lift(_ pointer: UnsafeMutableRawPointer) throws -> Fingerprinter {
        return Fingerprinter(unsafeFromRawPointer: pointer)
    }

    public static func lower(_ value: Fingerprinter) -> UnsafeMutableRawPointer {
        return value.uniffiClonePointer()
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Fingerprinter {
        let v: UInt64 = try readInt(&buf)
        // The Rust code won't compile if a pointer won't fit in a UInt64.
        // We have to go via `UInt` because that's the thing that's the size of a pointer.
        let ptr = UnsafeMutableRawPointer(bitPattern: UInt(truncatingIfNeeded: v))
        if ptr == nil {
            throw UniffiInternalError.unexpectedNullPointer
        }
        return try lift(ptr!)
    }

    public static func write(_ value: Fingerprinter, into buf: inout [UInt8]) {
        // This fiddling is because `Int` is the thing that's the same size as a pointer.
        // The Rust code won't compile if a pointer won't fit in a `UInt64`.
        writeInt(&buf, UInt64(bitPattern: Int64(Int(bitPattern: lower(value)))))
    }
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
public func FfiConverterTypeFingerprinter_lift(_ pointer: UnsafeMutableRawPointer) throws -> Fingerprinter {
    return try FfiConverterTypeFingerprinter.lift(pointer)
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
public func FfiConverterTypeFingerprinter_lower(_ value: Fingerprinter) -> UnsafeMutableRawPointer {
    return FfiConverterTypeFingerprinter.lower(value)
}

/**
 * Streaming fingerprinter that accepts PCM samples incrementally.
 *
 * Use this when you have a live audio stream or PCM buffers (e.g., iOS AVAudioPCMBuffer)
 * instead of a complete audio file.
 */
public protocol StreamingFingerprinterProtocol: AnyObject {
    /**
     * Total audio duration processed so far in milliseconds.
     */
    func durationMs() -> UInt32

    /**
     * Flush remaining state and return final hashes. Call when stream ends.
     */
    func flush() -> [UInt32]

    /**
     * Feed PCM samples (i16 format). Returns any new fingerprint hashes produced.
     */
    func pushSamples(samples: [Int16]) -> [UInt32]

    /**
     * Feed PCM samples (f32 format). Returns any new fingerprint hashes produced.
     * Use this for iOS AVAudioPCMBuffer float data.
     */
    func pushSamplesF32(samples: [Float], channels: UInt16) -> [UInt32]

    /**
     * Reset all state for a new stream.
     */
    func reset()
}

/**
 * Streaming fingerprinter that accepts PCM samples incrementally.
 *
 * Use this when you have a live audio stream or PCM buffers (e.g., iOS AVAudioPCMBuffer)
 * instead of a complete audio file.
 */
open class StreamingFingerprinter:
    StreamingFingerprinterProtocol
{
    fileprivate let pointer: UnsafeMutableRawPointer!

    // Used to instantiate a [FFIObject] without an actual pointer, for fakes in tests, mostly.
    #if swift(>=5.8)
        @_documentation(visibility: private)
    #endif
    public struct NoPointer {
        public init() {}
    }

    // TODO: We'd like this to be `private` but for Swifty reasons,
    // we can't implement `FfiConverter` without making this `required` and we can't
    // make it `required` without making it `public`.
    public required init(unsafeFromRawPointer pointer: UnsafeMutableRawPointer) {
        self.pointer = pointer
    }

    // This constructor can be used to instantiate a fake object.
    // - Parameter noPointer: Placeholder value so we can have a constructor separate from the default empty one that may be implemented for classes extending [FFIObject].
    //
    // - Warning:
    //     Any object instantiated with this constructor cannot be passed to an actual Rust-backed object. Since there isn't a backing [Pointer] the FFI lower functions will crash.
    #if swift(>=5.8)
        @_documentation(visibility: private)
    #endif
    public init(noPointer _: NoPointer) {
        pointer = nil
    }

    #if swift(>=5.8)
        @_documentation(visibility: private)
    #endif
    public func uniffiClonePointer() -> UnsafeMutableRawPointer {
        return try! rustCall { uniffi_fingerprint_uniffi_fn_clone_streamingfingerprinter(self.pointer, $0) }
    }

    /**
     * Create a new streaming fingerprinter.
     *
     * # Arguments
     * * `sample_rate` - Sample rate of incoming PCM data (e.g., 44100, 48000).
     * * `channels` - Number of audio channels (1 = mono, 2 = stereo).
     */
    public convenience init(sampleRate: UInt32, channels: UInt16) {
        let pointer =
            try! rustCall {
                uniffi_fingerprint_uniffi_fn_constructor_streamingfingerprinter_new(
                    FfiConverterUInt32.lower(sampleRate),
                    FfiConverterUInt16.lower(channels), $0
                )
            }
        self.init(unsafeFromRawPointer: pointer)
    }

    deinit {
        guard let pointer = pointer else {
            return
        }

        try! rustCall { uniffi_fingerprint_uniffi_fn_free_streamingfingerprinter(pointer, $0) }
    }

    /**
     * Total audio duration processed so far in milliseconds.
     */
    open func durationMs() -> UInt32 {
        return try! FfiConverterUInt32.lift(try! rustCall {
            uniffi_fingerprint_uniffi_fn_method_streamingfingerprinter_duration_ms(self.uniffiClonePointer(), $0)
        })
    }

    /**
     * Flush remaining state and return final hashes. Call when stream ends.
     */
    open func flush() -> [UInt32] {
        return try! FfiConverterSequenceUInt32.lift(try! rustCall {
            uniffi_fingerprint_uniffi_fn_method_streamingfingerprinter_flush(self.uniffiClonePointer(), $0)
        })
    }

    /**
     * Feed PCM samples (i16 format). Returns any new fingerprint hashes produced.
     */
    open func pushSamples(samples: [Int16]) -> [UInt32] {
        return try! FfiConverterSequenceUInt32.lift(try! rustCall {
            uniffi_fingerprint_uniffi_fn_method_streamingfingerprinter_push_samples(self.uniffiClonePointer(),
                                                                                    FfiConverterSequenceInt16.lower(samples), $0)
        })
    }

    /**
     * Feed PCM samples (f32 format). Returns any new fingerprint hashes produced.
     * Use this for iOS AVAudioPCMBuffer float data.
     */
    open func pushSamplesF32(samples: [Float], channels: UInt16) -> [UInt32] {
        return try! FfiConverterSequenceUInt32.lift(try! rustCall {
            uniffi_fingerprint_uniffi_fn_method_streamingfingerprinter_push_samples_f32(self.uniffiClonePointer(),
                                                                                        FfiConverterSequenceFloat.lower(samples),
                                                                                        FfiConverterUInt16.lower(channels), $0)
        })
    }

    /**
     * Reset all state for a new stream.
     */
    open func reset() {
        try! rustCall {
            uniffi_fingerprint_uniffi_fn_method_streamingfingerprinter_reset(self.uniffiClonePointer(), $0)
        }
    }
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
public struct FfiConverterTypeStreamingFingerprinter: FfiConverter {
    typealias FfiType = UnsafeMutableRawPointer
    typealias SwiftType = StreamingFingerprinter

    public static func lift(_ pointer: UnsafeMutableRawPointer) throws -> StreamingFingerprinter {
        return StreamingFingerprinter(unsafeFromRawPointer: pointer)
    }

    public static func lower(_ value: StreamingFingerprinter) -> UnsafeMutableRawPointer {
        return value.uniffiClonePointer()
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> StreamingFingerprinter {
        let v: UInt64 = try readInt(&buf)
        // The Rust code won't compile if a pointer won't fit in a UInt64.
        // We have to go via `UInt` because that's the thing that's the size of a pointer.
        let ptr = UnsafeMutableRawPointer(bitPattern: UInt(truncatingIfNeeded: v))
        if ptr == nil {
            throw UniffiInternalError.unexpectedNullPointer
        }
        return try lift(ptr!)
    }

    public static func write(_ value: StreamingFingerprinter, into buf: inout [UInt8]) {
        // This fiddling is because `Int` is the thing that's the same size as a pointer.
        // The Rust code won't compile if a pointer won't fit in a `UInt64`.
        writeInt(&buf, UInt64(bitPattern: Int64(Int(bitPattern: lower(value)))))
    }
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
public func FfiConverterTypeStreamingFingerprinter_lift(_ pointer: UnsafeMutableRawPointer) throws -> StreamingFingerprinter {
    return try FfiConverterTypeStreamingFingerprinter.lift(pointer)
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
public func FfiConverterTypeStreamingFingerprinter_lower(_ value: StreamingFingerprinter) -> UnsafeMutableRawPointer {
    return FfiConverterTypeStreamingFingerprinter.lower(value)
}

/**
 * Streaming windowed fingerprinter that produces fingerprints identical to
 * the batch `Fingerprinter.fingerprintDataWindowed()`, but accepts PCM samples
 * incrementally. Use this for real-time audio from iOS AVAudioPCMBuffer or
 * Android AudioRecord.
 */
public protocol StreamingWindowedFingerprinterProtocol: AnyObject {
    /**
     * Total audio duration buffered so far in milliseconds.
     */
    func durationMs() -> UInt32

    /**
     * Flush remaining windows.
     */
    func flush() -> [WindowedFingerprint]

    /**
     * Feed PCM samples (i16). Returns new windowed fingerprints.
     */
    func pushSamples(samples: [Int16]) -> [WindowedFingerprint]

    /**
     * Feed PCM samples (f32). Returns new windowed fingerprints.
     */
    func pushSamplesF32(samples: [Float], channels: UInt16) -> [WindowedFingerprint]

    /**
     * Reset all state.
     */
    func reset()
}

/**
 * Streaming windowed fingerprinter that produces fingerprints identical to
 * the batch `Fingerprinter.fingerprintDataWindowed()`, but accepts PCM samples
 * incrementally. Use this for real-time audio from iOS AVAudioPCMBuffer or
 * Android AudioRecord.
 */
open class StreamingWindowedFingerprinter:
    StreamingWindowedFingerprinterProtocol
{
    fileprivate let pointer: UnsafeMutableRawPointer!

    // Used to instantiate a [FFIObject] without an actual pointer, for fakes in tests, mostly.
    #if swift(>=5.8)
        @_documentation(visibility: private)
    #endif
    public struct NoPointer {
        public init() {}
    }

    // TODO: We'd like this to be `private` but for Swifty reasons,
    // we can't implement `FfiConverter` without making this `required` and we can't
    // make it `required` without making it `public`.
    public required init(unsafeFromRawPointer pointer: UnsafeMutableRawPointer) {
        self.pointer = pointer
    }

    // This constructor can be used to instantiate a fake object.
    // - Parameter noPointer: Placeholder value so we can have a constructor separate from the default empty one that may be implemented for classes extending [FFIObject].
    //
    // - Warning:
    //     Any object instantiated with this constructor cannot be passed to an actual Rust-backed object. Since there isn't a backing [Pointer] the FFI lower functions will crash.
    #if swift(>=5.8)
        @_documentation(visibility: private)
    #endif
    public init(noPointer _: NoPointer) {
        pointer = nil
    }

    #if swift(>=5.8)
        @_documentation(visibility: private)
    #endif
    public func uniffiClonePointer() -> UnsafeMutableRawPointer {
        return try! rustCall { uniffi_fingerprint_uniffi_fn_clone_streamingwindowedfingerprinter(self.pointer, $0) }
    }

    /**
     * Create a new streaming windowed fingerprinter.
     *
     * # Arguments
     * * `sample_rate` - Sample rate of incoming PCM data (e.g., 44100, 48000)
     * * `channels` - Number of channels (1=mono, 2=stereo)
     * * `window_duration_ms` - Duration of each fingerprint window (e.g., 10000)
     * * `window_interval_ms` - Interval between windows (e.g., 2000)
     */
    public convenience init(sampleRate: UInt32, channels: UInt16, windowDurationMs: UInt32, windowIntervalMs: UInt32) {
        let pointer =
            try! rustCall {
                uniffi_fingerprint_uniffi_fn_constructor_streamingwindowedfingerprinter_new(
                    FfiConverterUInt32.lower(sampleRate),
                    FfiConverterUInt16.lower(channels),
                    FfiConverterUInt32.lower(windowDurationMs),
                    FfiConverterUInt32.lower(windowIntervalMs), $0
                )
            }
        self.init(unsafeFromRawPointer: pointer)
    }

    deinit {
        guard let pointer = pointer else {
            return
        }

        try! rustCall { uniffi_fingerprint_uniffi_fn_free_streamingwindowedfingerprinter(pointer, $0) }
    }

    /**
     * Total audio duration buffered so far in milliseconds.
     */
    open func durationMs() -> UInt32 {
        return try! FfiConverterUInt32.lift(try! rustCall {
            uniffi_fingerprint_uniffi_fn_method_streamingwindowedfingerprinter_duration_ms(self.uniffiClonePointer(), $0)
        })
    }

    /**
     * Flush remaining windows.
     */
    open func flush() -> [WindowedFingerprint] {
        return try! FfiConverterSequenceTypeWindowedFingerprint.lift(try! rustCall {
            uniffi_fingerprint_uniffi_fn_method_streamingwindowedfingerprinter_flush(self.uniffiClonePointer(), $0)
        })
    }

    /**
     * Feed PCM samples (i16). Returns new windowed fingerprints.
     */
    open func pushSamples(samples: [Int16]) -> [WindowedFingerprint] {
        return try! FfiConverterSequenceTypeWindowedFingerprint.lift(try! rustCall {
            uniffi_fingerprint_uniffi_fn_method_streamingwindowedfingerprinter_push_samples(self.uniffiClonePointer(),
                                                                                            FfiConverterSequenceInt16.lower(samples), $0)
        })
    }

    /**
     * Feed PCM samples (f32). Returns new windowed fingerprints.
     */
    open func pushSamplesF32(samples: [Float], channels: UInt16) -> [WindowedFingerprint] {
        return try! FfiConverterSequenceTypeWindowedFingerprint.lift(try! rustCall {
            uniffi_fingerprint_uniffi_fn_method_streamingwindowedfingerprinter_push_samples_f32(self.uniffiClonePointer(),
                                                                                                FfiConverterSequenceFloat.lower(samples),
                                                                                                FfiConverterUInt16.lower(channels), $0)
        })
    }

    /**
     * Reset all state.
     */
    open func reset() {
        try! rustCall {
            uniffi_fingerprint_uniffi_fn_method_streamingwindowedfingerprinter_reset(self.uniffiClonePointer(), $0)
        }
    }
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
public struct FfiConverterTypeStreamingWindowedFingerprinter: FfiConverter {
    typealias FfiType = UnsafeMutableRawPointer
    typealias SwiftType = StreamingWindowedFingerprinter

    public static func lift(_ pointer: UnsafeMutableRawPointer) throws -> StreamingWindowedFingerprinter {
        return StreamingWindowedFingerprinter(unsafeFromRawPointer: pointer)
    }

    public static func lower(_ value: StreamingWindowedFingerprinter) -> UnsafeMutableRawPointer {
        return value.uniffiClonePointer()
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> StreamingWindowedFingerprinter {
        let v: UInt64 = try readInt(&buf)
        // The Rust code won't compile if a pointer won't fit in a UInt64.
        // We have to go via `UInt` because that's the thing that's the size of a pointer.
        let ptr = UnsafeMutableRawPointer(bitPattern: UInt(truncatingIfNeeded: v))
        if ptr == nil {
            throw UniffiInternalError.unexpectedNullPointer
        }
        return try lift(ptr!)
    }

    public static func write(_ value: StreamingWindowedFingerprinter, into buf: inout [UInt8]) {
        // This fiddling is because `Int` is the thing that's the same size as a pointer.
        // The Rust code won't compile if a pointer won't fit in a `UInt64`.
        writeInt(&buf, UInt64(bitPattern: Int64(Int(bitPattern: lower(value)))))
    }
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
public func FfiConverterTypeStreamingWindowedFingerprinter_lift(_ pointer: UnsafeMutableRawPointer) throws -> StreamingWindowedFingerprinter {
    return try FfiConverterTypeStreamingWindowedFingerprinter.lift(pointer)
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
public func FfiConverterTypeStreamingWindowedFingerprinter_lower(_ value: StreamingWindowedFingerprinter) -> UnsafeMutableRawPointer {
    return FfiConverterTypeStreamingWindowedFingerprinter.lower(value)
}

/**
 * A fingerprint result containing hash data and duration.
 */
public struct FingerprintData {
    /**
     * Raw hash values.
     */
    public var hashes: [UInt32]
    /**
     * Duration of the audio in milliseconds.
     */
    public var durationMs: UInt32

    /// Default memberwise initializers are never public by default, so we
    /// declare one manually.
    public init(
        /* 
         * Raw hash values.
         */ hashes: [UInt32],
        /* 
            * Duration of the audio in milliseconds.
            */ durationMs: UInt32
    ) {
        self.hashes = hashes
        self.durationMs = durationMs
    }
}

extension FingerprintData: Equatable, Hashable {
    public static func == (lhs: FingerprintData, rhs: FingerprintData) -> Bool {
        if lhs.hashes != rhs.hashes {
            return false
        }
        if lhs.durationMs != rhs.durationMs {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(hashes)
        hasher.combine(durationMs)
    }
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
public struct FfiConverterTypeFingerprintData: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> FingerprintData {
        return
            try FingerprintData(
                hashes: FfiConverterSequenceUInt32.read(from: &buf),
                durationMs: FfiConverterUInt32.read(from: &buf)
            )
    }

    public static func write(_ value: FingerprintData, into buf: inout [UInt8]) {
        FfiConverterSequenceUInt32.write(value.hashes, into: &buf)
        FfiConverterUInt32.write(value.durationMs, into: &buf)
    }
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
public func FfiConverterTypeFingerprintData_lift(_ buf: RustBuffer) throws -> FingerprintData {
    return try FfiConverterTypeFingerprintData.lift(buf)
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
public func FfiConverterTypeFingerprintData_lower(_ value: FingerprintData) -> RustBuffer {
    return FfiConverterTypeFingerprintData.lower(value)
}

/**
 * Result of a checkpoint match.
 */
public struct MatchResult {
    /**
     * Timestamp of the matched checkpoint in seconds.
     */
    public var timestamp: Float
    /**
     * Similarity score (0.0 to 1.0).
     */
    public var score: Float

    /// Default memberwise initializers are never public by default, so we
    /// declare one manually.
    public init(
        /* 
         * Timestamp of the matched checkpoint in seconds.
         */ timestamp: Float,
        /* 
            * Similarity score (0.0 to 1.0).
            */ score: Float
    ) {
        self.timestamp = timestamp
        self.score = score
    }
}

extension MatchResult: Equatable, Hashable {
    public static func == (lhs: MatchResult, rhs: MatchResult) -> Bool {
        if lhs.timestamp != rhs.timestamp {
            return false
        }
        if lhs.score != rhs.score {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(timestamp)
        hasher.combine(score)
    }
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
public struct FfiConverterTypeMatchResult: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> MatchResult {
        return
            try MatchResult(
                timestamp: FfiConverterFloat.read(from: &buf),
                score: FfiConverterFloat.read(from: &buf)
            )
    }

    public static func write(_ value: MatchResult, into buf: inout [UInt8]) {
        FfiConverterFloat.write(value.timestamp, into: &buf)
        FfiConverterFloat.write(value.score, into: &buf)
    }
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
public func FfiConverterTypeMatchResult_lift(_ buf: RustBuffer) throws -> MatchResult {
    return try FfiConverterTypeMatchResult.lift(buf)
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
public func FfiConverterTypeMatchResult_lower(_ value: MatchResult) -> RustBuffer {
    return FfiConverterTypeMatchResult.lower(value)
}

/**
 * A windowed fingerprint with timestamp information.
 */
public struct WindowedFingerprint {
    /**
     * Timestamp in milliseconds from the start of the audio.
     */
    public var timestampMs: UInt32
    /**
     * Duration of the fingerprinted segment in milliseconds.
     */
    public var durationMs: UInt32
    /**
     * Raw hash values.
     */
    public var hashes: [UInt32]

    /// Default memberwise initializers are never public by default, so we
    /// declare one manually.
    public init(
        /* 
         * Timestamp in milliseconds from the start of the audio.
         */ timestampMs: UInt32,
        /* 
            * Duration of the fingerprinted segment in milliseconds.
            */ durationMs: UInt32,
        /* 
            * Raw hash values.
            */ hashes: [UInt32]
    ) {
        self.timestampMs = timestampMs
        self.durationMs = durationMs
        self.hashes = hashes
    }
}

extension WindowedFingerprint: Equatable, Hashable {
    public static func == (lhs: WindowedFingerprint, rhs: WindowedFingerprint) -> Bool {
        if lhs.timestampMs != rhs.timestampMs {
            return false
        }
        if lhs.durationMs != rhs.durationMs {
            return false
        }
        if lhs.hashes != rhs.hashes {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(timestampMs)
        hasher.combine(durationMs)
        hasher.combine(hashes)
    }
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
public struct FfiConverterTypeWindowedFingerprint: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> WindowedFingerprint {
        return
            try WindowedFingerprint(
                timestampMs: FfiConverterUInt32.read(from: &buf),
                durationMs: FfiConverterUInt32.read(from: &buf),
                hashes: FfiConverterSequenceUInt32.read(from: &buf)
            )
    }

    public static func write(_ value: WindowedFingerprint, into buf: inout [UInt8]) {
        FfiConverterUInt32.write(value.timestampMs, into: &buf)
        FfiConverterUInt32.write(value.durationMs, into: &buf)
        FfiConverterSequenceUInt32.write(value.hashes, into: &buf)
    }
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
public func FfiConverterTypeWindowedFingerprint_lift(_ buf: RustBuffer) throws -> WindowedFingerprint {
    return try FfiConverterTypeWindowedFingerprint.lift(buf)
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
public func FfiConverterTypeWindowedFingerprint_lower(_ value: WindowedFingerprint) -> RustBuffer {
    return FfiConverterTypeWindowedFingerprint.lower(value)
}

/**
 * Error type for fingerprinting operations.
 */
public enum FingerprintError {
    case DecodeError(message: String)
    case UnsupportedFormat(message: String)
    case InvalidInput(message: String)
    case IoError(message: String)
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
public struct FfiConverterTypeFingerprintError: FfiConverterRustBuffer {
    typealias SwiftType = FingerprintError

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> FingerprintError {
        let variant: Int32 = try readInt(&buf)
        switch variant {
        case 1: return try .DecodeError(
                message: FfiConverterString.read(from: &buf)
            )
        case 2: return try .UnsupportedFormat(
                message: FfiConverterString.read(from: &buf)
            )
        case 3: return try .InvalidInput(
                message: FfiConverterString.read(from: &buf)
            )
        case 4: return try .IoError(
                message: FfiConverterString.read(from: &buf)
            )
        default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: FingerprintError, into buf: inout [UInt8]) {
        switch value {
        case let .DecodeError(message):
            writeInt(&buf, Int32(1))
            FfiConverterString.write(message, into: &buf)

        case let .UnsupportedFormat(message):
            writeInt(&buf, Int32(2))
            FfiConverterString.write(message, into: &buf)

        case let .InvalidInput(message):
            writeInt(&buf, Int32(3))
            FfiConverterString.write(message, into: &buf)

        case let .IoError(message):
            writeInt(&buf, Int32(4))
            FfiConverterString.write(message, into: &buf)
        }
    }
}

extension FingerprintError: Equatable, Hashable {}

extension FingerprintError: Foundation.LocalizedError {
    public var errorDescription: String? {
        String(reflecting: self)
    }
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
private struct FfiConverterOptionTypeFingerprintData: FfiConverterRustBuffer {
    typealias SwiftType = FingerprintData?

    static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterTypeFingerprintData.write(value, into: &buf)
    }

    static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterTypeFingerprintData.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
private struct FfiConverterSequenceInt16: FfiConverterRustBuffer {
    typealias SwiftType = [Int16]

    static func write(_ value: [Int16], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterInt16.write(item, into: &buf)
        }
    }

    static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [Int16] {
        let len: Int32 = try readInt(&buf)
        var seq = [Int16]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            try seq.append(FfiConverterInt16.read(from: &buf))
        }
        return seq
    }
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
private struct FfiConverterSequenceUInt32: FfiConverterRustBuffer {
    typealias SwiftType = [UInt32]

    static func write(_ value: [UInt32], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterUInt32.write(item, into: &buf)
        }
    }

    static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [UInt32] {
        let len: Int32 = try readInt(&buf)
        var seq = [UInt32]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            try seq.append(FfiConverterUInt32.read(from: &buf))
        }
        return seq
    }
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
private struct FfiConverterSequenceFloat: FfiConverterRustBuffer {
    typealias SwiftType = [Float]

    static func write(_ value: [Float], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterFloat.write(item, into: &buf)
        }
    }

    static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [Float] {
        let len: Int32 = try readInt(&buf)
        var seq = [Float]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            try seq.append(FfiConverterFloat.read(from: &buf))
        }
        return seq
    }
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
private struct FfiConverterSequenceTypeMatchResult: FfiConverterRustBuffer {
    typealias SwiftType = [MatchResult]

    static func write(_ value: [MatchResult], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterTypeMatchResult.write(item, into: &buf)
        }
    }

    static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [MatchResult] {
        let len: Int32 = try readInt(&buf)
        var seq = [MatchResult]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            try seq.append(FfiConverterTypeMatchResult.read(from: &buf))
        }
        return seq
    }
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
private struct FfiConverterSequenceTypeWindowedFingerprint: FfiConverterRustBuffer {
    typealias SwiftType = [WindowedFingerprint]

    static func write(_ value: [WindowedFingerprint], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterTypeWindowedFingerprint.write(item, into: &buf)
        }
    }

    static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [WindowedFingerprint] {
        let len: Int32 = try readInt(&buf)
        var seq = [WindowedFingerprint]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            try seq.append(FfiConverterTypeWindowedFingerprint.read(from: &buf))
        }
        return seq
    }
}

/**
 * Compare two fingerprint hash arrays without drift compensation.
 *
 * # Arguments
 * * `hashes1` - First fingerprint hash array.
 * * `hashes2` - Second fingerprint hash array.
 *
 * # Returns
 * Similarity score between 0.0 (completely different) and 1.0 (identical).
 */
public func compareHashes(hashes1: [UInt32], hashes2: [UInt32]) -> Float {
    return try! FfiConverterFloat.lift(try! rustCall {
        uniffi_fingerprint_uniffi_fn_func_compare_hashes(
            FfiConverterSequenceUInt32.lower(hashes1),
            FfiConverterSequenceUInt32.lower(hashes2), $0
        )
    })
}

/**
 * Compare two fingerprint hash arrays with drift compensation.
 *
 * This is the unified comparison function for all platforms.
 *
 * # Arguments
 * * `hashes1` - First fingerprint hash array.
 * * `hashes2` - Second fingerprint hash array.
 * * `max_drift` - Maximum number of hash positions to shift for alignment (0 = no drift).
 *
 * # Returns
 * Similarity score between 0.0 (completely different) and 1.0 (identical).
 */
public func compareHashesWithDrift(hashes1: [UInt32], hashes2: [UInt32], maxDrift: UInt32) -> Float {
    return try! FfiConverterFloat.lift(try! rustCall {
        uniffi_fingerprint_uniffi_fn_func_compare_hashes_with_drift(
            FfiConverterSequenceUInt32.lower(hashes1),
            FfiConverterSequenceUInt32.lower(hashes2),
            FfiConverterUInt32.lower(maxDrift), $0
        )
    })
}

/**
 * Create a FingerprintData from raw bytes.
 *
 * # Arguments
 * * `data` - Serialized fingerprint bytes.
 *
 * # Returns
 * FingerprintData if parsing succeeded, None otherwise.
 */
public func fingerprintFromBytes(data: Data) -> FingerprintData? {
    return try! FfiConverterOptionTypeFingerprintData.lift(try! rustCall {
        uniffi_fingerprint_uniffi_fn_func_fingerprint_from_bytes(
            FfiConverterData.lower(data), $0
        )
    })
}

/**
 * Serialize a fingerprint to bytes.
 *
 * # Arguments
 * * `hashes` - Fingerprint hash values.
 * * `duration_ms` - Duration in milliseconds.
 *
 * # Returns
 * Serialized fingerprint bytes.
 */
public func fingerprintToBytes(hashes: [UInt32], durationMs: UInt32) -> Data {
    return try! FfiConverterData.lift(try! rustCall {
        uniffi_fingerprint_uniffi_fn_func_fingerprint_to_bytes(
            FfiConverterSequenceUInt32.lower(hashes),
            FfiConverterUInt32.lower(durationMs), $0
        )
    })
}

/**
 * Get the library version.
 */
public func fingerprintVersion() -> String {
    return try! FfiConverterString.lift(try! rustCall {
        uniffi_fingerprint_uniffi_fn_func_fingerprint_version($0)
    })
}

private enum InitializationResult {
    case ok
    case contractVersionMismatch
    case apiChecksumMismatch
}

/// Use a global variable to perform the versioning checks. Swift ensures that
/// the code inside is only computed once.
private var initializationResult: InitializationResult = {
    // Get the bindings contract version from our ComponentInterface
    let bindings_contract_version = 26
    // Get the scaffolding contract version by calling the into the dylib
    let scaffolding_contract_version = ffi_fingerprint_uniffi_uniffi_contract_version()
    if bindings_contract_version != scaffolding_contract_version {
        return InitializationResult.contractVersionMismatch
    }
    if uniffi_fingerprint_uniffi_checksum_func_compare_hashes() != 45225 {
        return InitializationResult.apiChecksumMismatch
    }
    if uniffi_fingerprint_uniffi_checksum_func_compare_hashes_with_drift() != 15612 {
        return InitializationResult.apiChecksumMismatch
    }
    if uniffi_fingerprint_uniffi_checksum_func_fingerprint_from_bytes() != 12133 {
        return InitializationResult.apiChecksumMismatch
    }
    if uniffi_fingerprint_uniffi_checksum_func_fingerprint_to_bytes() != 28275 {
        return InitializationResult.apiChecksumMismatch
    }
    if uniffi_fingerprint_uniffi_checksum_func_fingerprint_version() != 19514 {
        return InitializationResult.apiChecksumMismatch
    }
    if uniffi_fingerprint_uniffi_checksum_method_checkpointmatcher_add() != 23023 {
        return InitializationResult.apiChecksumMismatch
    }
    if uniffi_fingerprint_uniffi_checksum_method_checkpointmatcher_clear() != 24320 {
        return InitializationResult.apiChecksumMismatch
    }
    if uniffi_fingerprint_uniffi_checksum_method_checkpointmatcher_count() != 40735 {
        return InitializationResult.apiChecksumMismatch
    }
    if uniffi_fingerprint_uniffi_checksum_method_checkpointmatcher_find_top_matches() != 16142 {
        return InitializationResult.apiChecksumMismatch
    }
    if uniffi_fingerprint_uniffi_checksum_method_checkpointmatcher_set_drift() != 28233 {
        return InitializationResult.apiChecksumMismatch
    }
    if uniffi_fingerprint_uniffi_checksum_method_fingerprinter_fingerprint_data_windowed() != 19267 {
        return InitializationResult.apiChecksumMismatch
    }
    if uniffi_fingerprint_uniffi_checksum_method_streamingfingerprinter_duration_ms() != 48437 {
        return InitializationResult.apiChecksumMismatch
    }
    if uniffi_fingerprint_uniffi_checksum_method_streamingfingerprinter_flush() != 10649 {
        return InitializationResult.apiChecksumMismatch
    }
    if uniffi_fingerprint_uniffi_checksum_method_streamingfingerprinter_push_samples() != 22690 {
        return InitializationResult.apiChecksumMismatch
    }
    if uniffi_fingerprint_uniffi_checksum_method_streamingfingerprinter_push_samples_f32() != 35686 {
        return InitializationResult.apiChecksumMismatch
    }
    if uniffi_fingerprint_uniffi_checksum_method_streamingfingerprinter_reset() != 53798 {
        return InitializationResult.apiChecksumMismatch
    }
    if uniffi_fingerprint_uniffi_checksum_method_streamingwindowedfingerprinter_duration_ms() != 52027 {
        return InitializationResult.apiChecksumMismatch
    }
    if uniffi_fingerprint_uniffi_checksum_method_streamingwindowedfingerprinter_flush() != 55098 {
        return InitializationResult.apiChecksumMismatch
    }
    if uniffi_fingerprint_uniffi_checksum_method_streamingwindowedfingerprinter_push_samples() != 6835 {
        return InitializationResult.apiChecksumMismatch
    }
    if uniffi_fingerprint_uniffi_checksum_method_streamingwindowedfingerprinter_push_samples_f32() != 17811 {
        return InitializationResult.apiChecksumMismatch
    }
    if uniffi_fingerprint_uniffi_checksum_method_streamingwindowedfingerprinter_reset() != 36251 {
        return InitializationResult.apiChecksumMismatch
    }
    if uniffi_fingerprint_uniffi_checksum_constructor_checkpointmatcher_new() != 35825 {
        return InitializationResult.apiChecksumMismatch
    }
    if uniffi_fingerprint_uniffi_checksum_constructor_checkpointmatcher_with_drift() != 32672 {
        return InitializationResult.apiChecksumMismatch
    }
    if uniffi_fingerprint_uniffi_checksum_constructor_fingerprinter_new() != 57593 {
        return InitializationResult.apiChecksumMismatch
    }
    if uniffi_fingerprint_uniffi_checksum_constructor_streamingfingerprinter_new() != 12582 {
        return InitializationResult.apiChecksumMismatch
    }
    if uniffi_fingerprint_uniffi_checksum_constructor_streamingwindowedfingerprinter_new() != 25360 {
        return InitializationResult.apiChecksumMismatch
    }

    return InitializationResult.ok
}()

private func uniffiEnsureInitialized() {
    switch initializationResult {
    case .ok:
        break
    case .contractVersionMismatch:
        fatalError("UniFFI contract version mismatch: try cleaning and rebuilding your project")
    case .apiChecksumMismatch:
        fatalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
}

// swiftlint:enable all
