import XCTest
import GRDB
@testable import PocketCastsDataModel
@testable import PocketCastsUtils

/// Tests that validate the SQL queries generated by GRDB QueryInterface
/// match the raw SQL queries in the SQL implementation for AutoAddCandidatesDataManager.
///
/// These tests work by:
/// 1. Calling the SQL implementation method with a capturing database queue
/// 2. Extracting the SQL from the equivalent GRDB QueryInterface request
/// 3. Comparing the two SQL strings to ensure they match
final class AutoAddCandidatesDataManagerQueryTests: SQLQueryComparisonTestCase {

    // MARK: - Test Setup

    private var autoAddCandidatesDataManager: AutoAddCandidatesDataManager!

    override func setUp() async throws {
        try await super.setUp()
        autoAddCandidatesDataManager = AutoAddCandidatesDataManager(dbQueue: sqlCapturingQueue)

        // Create the schema in GRDB for SQL extraction
        try await grdbQueue.write { db in
            try db.create(table: AutoAddCandidateRecord.databaseTableName, ifNotExists: true) { t in
                t.autoIncrementedPrimaryKey("id")
                t.column("episode_uuid", .text).notNull().defaults(to: "")
                t.column("podcast_uuid", .text).notNull().defaults(to: "")
            }
        }
    }

    override func tearDown() async throws {
        autoAddCandidatesDataManager = nil
        try await super.tearDown()
    }

    // MARK: - Add Candidate Query Tests

    func testAddCandidateQuery() throws {
        // Call the SQL implementation to capture the query
        autoAddCandidatesDataManager.add(podcastUUID: "podcast-uuid", episodeUUID: "episode-uuid")
        let capturedSQL = sqlCapturingQueue.lastCapturedSQL!

        // Build the equivalent GRDB query - for INSERT we compare the structure
        // GRDB uses record.insert() which generates similar SQL
        var record = AutoAddCandidateRecord()
        record.podcast_uuid = "podcast-uuid"
        record.episode_uuid = "episode-uuid"

        var grdbSQL: String?
        try grdbQueue.write { db in
            db.trace { event in
                if case let .statement(statement) = event {
                    let sql = statement.expandedSQL
                    if sql.uppercased().hasPrefix("INSERT") {
                        grdbSQL = sql
                    }
                }
            }
            try record.insert(db)
            db.trace(nil)
        }

        // Compare the SQL
        assertSQLEquivalent(capturedSQL, grdbSQL!)
    }

    // MARK: - Remove Candidate Query Tests

    func testRemoveCandidateQuery() throws {
        // Create a mock candidate using the mock result set
        let mockResultSet = MockAutoAddCandidateResultSet(
            id: 123,
            setting: .addLast,
            episodeUuid: "episode-uuid"
        )
        guard let candidate = AutoAddCandidatesDataManager.AutoAddCandidate(from: mockResultSet) else {
            XCTFail("Failed to create mock candidate")
            return
        }

        // Call the SQL implementation to capture the query
        autoAddCandidatesDataManager.remove(candidate)
        let capturedSQL = sqlCapturingQueue.lastCapturedSQL!

        // Build the equivalent GRDB query
        let grdbRequest = AutoAddCandidateRecord
            .filter(AutoAddCandidateRecord.Columns.id == Int64(123))
            .limit(1)
        let grdbSQL = try extractDeleteSQL(grdbRequest)

        // Compare the SQL
        assertSQLEquivalent(capturedSQL, grdbSQL)
    }

    // MARK: - Clear All Candidates Query Tests

    func testClearAllCandidatesQuery() throws {
        // Call the SQL implementation to capture the query
        autoAddCandidatesDataManager.clearAll()
        let capturedSQL = sqlCapturingQueue.lastCapturedSQL!

        // Build the equivalent GRDB query
        let grdbRequest = AutoAddCandidateRecord.all()
        let grdbSQL = try extractDeleteSQL(grdbRequest)

        // Compare the SQL
        assertSQLEquivalent(capturedSQL, grdbSQL)
    }
}

// MARK: - Test Helper

/// Mock result set for creating AutoAddCandidate instances in tests
private class MockAutoAddCandidateResultSet: PCDBResultSet {
    private let mockId: Int
    private let mockSetting: Int32
    private let mockEpisodeUuid: String
    private var didCallNext = false

    init(id: Int, setting: AutoAddToUpNextSetting, episodeUuid: String) {
        self.mockId = id
        self.mockSetting = setting.rawValue
        self.mockEpisodeUuid = episodeUuid
    }

    func next() -> Bool {
        if !didCallNext {
            didCallNext = true
            return true
        }
        return false
    }

    func close() {}
    func int(forColumn columnName: String) -> Int32 {
        if columnName == "auto_add_setting" { return mockSetting }
        return 0
    }
    func int(forColumnIndex columnIdx: Int32) -> Int32 { 0 }
    func long(forColumn columnName: String) -> Int { 0 }
    func long(forColumnIndex columnIdx: Int32) -> Int { 0 }
    func longLongInt(forColumn columnName: String) -> Int64 { 0 }
    func double(forColumn columnName: String) -> Double { 0 }
    func bool(forColumn columnName: String) -> Bool { false }
    func string(forColumn columnName: String) -> String? {
        if columnName == "episode_uuid" { return mockEpisodeUuid }
        return nil
    }
    func date(forColumn columnName: String) -> Date? { nil }
    func object(forColumn columnName: String) -> Any? {
        if columnName == "id" { return NSNumber(value: mockId) }
        return nil
    }
}
