import XCTest
import GRDB
@testable import PocketCastsDataModel
@testable import PocketCastsUtils

/// Tests that validate the SQL queries generated by GRDB QueryInterface
/// match the raw SQL queries in the SQL implementation for BookmarkDataManager.
///
/// These tests work by:
/// 1. Calling the SQL implementation method with a capturing database queue
/// 2. Calling the actual GRDB implementation method with a SQL-capturing GRDBQueue
/// 3. Comparing both:
///    - SQL structure (after normalization) to catch structural differences
///    - Execution plans (via EXPLAIN QUERY PLAN) to ensure SQLite treats them equivalently
///
/// This approach validates the actual production GRDB code, not manual query recreations.
final class BookmarkDataManagerQueryTests: SQLQueryComparisonTestCase {

    // MARK: - Test Setup

    private var bookmarkDataManager: BookmarkDataManager!
    private var grdbCapturingQueue: SQLCapturingGRDBQueue!

    override func setUp() async throws {
        try await super.setUp()
        bookmarkDataManager = BookmarkDataManager(dbQueue: sqlCapturingQueue)
        grdbCapturingQueue = try SQLCapturingGRDBQueue()

        // Create the schema in both GRDB queues for SQL extraction and execution
        try await grdbQueue.write { db in
            try db.create(table: Bookmark.databaseTableName, ifNotExists: true) { t in
                t.column("uuid", .text).notNull().primaryKey()
                t.column("title", .text).notNull().defaults(to: "")
                t.column("time", .double).notNull().defaults(to: 0)
                t.column("date_added", .double).notNull().defaults(to: 0)
                t.column("title_modified_date", .double)
                t.column("episode_uuid", .text).notNull().defaults(to: "")
                t.column("podcast_uuid", .text)
                t.column("sync_status", .integer).notNull().defaults(to: 0)
                t.column("deleted", .boolean).notNull().defaults(to: false)
                t.column("deleted_modified_date", .double)
            }
        }

        // Create the same schema in the capturing GRDB queue
        _ = grdbCapturingQueue.write { db in
            try db.create(table: Bookmark.databaseTableName, ifNotExists: true) { t in
                t.column("uuid", .text).notNull().primaryKey()
                t.column("title", .text).notNull().defaults(to: "")
                t.column("time", .double).notNull().defaults(to: 0)
                t.column("date_added", .double).notNull().defaults(to: 0)
                t.column("title_modified_date", .double)
                t.column("episode_uuid", .text).notNull().defaults(to: "")
                t.column("podcast_uuid", .text)
                t.column("sync_status", .integer).notNull().defaults(to: 0)
                t.column("deleted", .boolean).notNull().defaults(to: false)
                t.column("deleted_modified_date", .double)
            }
        }
    }

    override func tearDown() async throws {
        bookmarkDataManager = nil
        grdbCapturingQueue = nil
        try await super.tearDown()
    }

    // MARK: - Find Bookmark By UUID Query Tests

    func testBookmarkByUuidQueryAllowDeleted() throws {
        // Call the SQL implementation to capture the query
        _ = bookmarkDataManager.bookmark(for: "test-uuid", allowDeleted: true)
        let capturedSQL = sqlCapturingQueue.lastCapturedSQL!

        // Call the actual GRDB implementation to capture its query
        grdbCapturingQueue.clearCapturedSQL()
        _ = bookmarkDataManager.bookmarkGRDB(for: "test-uuid", allowDeleted: true, grdbQueue: grdbCapturingQueue)
        let grdbSQL = grdbCapturingQueue.lastCapturedSQL!

        // Validate both SQL structure and execution plan equivalence
        assertSQLEquivalent(capturedSQL, grdbSQL)
        try assertExecutionPlanEquivalent(capturedSQL, grdbSQL)
    }

    func testBookmarkByUuidQueryExcludeDeleted() throws {
        // Call the SQL implementation to capture the query
        _ = bookmarkDataManager.bookmark(for: "test-uuid", allowDeleted: false)
        let capturedSQL = sqlCapturingQueue.lastCapturedSQL!

        // Call the actual GRDB implementation to capture its query
        grdbCapturingQueue.clearCapturedSQL()
        _ = bookmarkDataManager.bookmarkGRDB(for: "test-uuid", allowDeleted: false, grdbQueue: grdbCapturingQueue)
        let grdbSQL = grdbCapturingQueue.lastCapturedSQL!

        // Validate both SQL structure and execution plan equivalence
        assertSQLEquivalent(capturedSQL, grdbSQL)
        try assertExecutionPlanEquivalent(capturedSQL, grdbSQL)
    }

    // MARK: - Existing Bookmark Query Tests

    func testExistingBookmarkQuery() throws {
        // Call the SQL implementation to capture the query
        _ = bookmarkDataManager.existingBookmark(forEpisode: "episode-uuid", time: 120.5)
        let capturedSQL = sqlCapturingQueue.lastCapturedSQL!

        // Call the actual GRDB implementation to capture its query
        grdbCapturingQueue.clearCapturedSQL()
        _ = bookmarkDataManager.existingBookmarkGRDB(forEpisode: "episode-uuid", time: 120.5, grdbQueue: grdbCapturingQueue)
        let grdbSQL = grdbCapturingQueue.lastCapturedSQL!

        // Validate both SQL structure and execution plan equivalence
        assertSQLEquivalent(capturedSQL, grdbSQL)
        try assertExecutionPlanEquivalent(capturedSQL, grdbSQL)
    }

    // MARK: - Bookmarks For Episode Query Tests

    func testBookmarksForEpisodeNewestToOldestQuery() throws {
        // Call the SQL implementation to capture the query
        _ = bookmarkDataManager.bookmarks(forEpisode: "episode-uuid", sorted: .newestToOldest)
        let capturedSQL = sqlCapturingQueue.lastCapturedSQL!

        // Call the actual GRDB implementation to capture its query
        grdbCapturingQueue.clearCapturedSQL()
        _ = bookmarkDataManager.bookmarksGRDB(forEpisode: "episode-uuid", sorted: .newestToOldest, grdbQueue: grdbCapturingQueue)
        let grdbSQL = grdbCapturingQueue.lastCapturedSQL!

        // Validate both SQL structure and execution plan equivalence
        assertSQLEquivalent(capturedSQL, grdbSQL)
        try assertExecutionPlanEquivalent(capturedSQL, grdbSQL)
    }

    func testBookmarksForEpisodeOldestToNewestQuery() throws {
        // Call the SQL implementation to capture the query
        _ = bookmarkDataManager.bookmarks(forEpisode: "episode-uuid", sorted: .oldestToNewest)
        let capturedSQL = sqlCapturingQueue.lastCapturedSQL!

        // Call the actual GRDB implementation to capture its query
        grdbCapturingQueue.clearCapturedSQL()
        _ = bookmarkDataManager.bookmarksGRDB(forEpisode: "episode-uuid", sorted: .oldestToNewest, grdbQueue: grdbCapturingQueue)
        let grdbSQL = grdbCapturingQueue.lastCapturedSQL!

        // Validate both SQL structure and execution plan equivalence
        assertSQLEquivalent(capturedSQL, grdbSQL)
        try assertExecutionPlanEquivalent(capturedSQL, grdbSQL)
    }

    func testBookmarksForEpisodeByTimestampQuery() throws {
        // Call the SQL implementation to capture the query
        _ = bookmarkDataManager.bookmarks(forEpisode: "episode-uuid", sorted: .timestamp)
        let capturedSQL = sqlCapturingQueue.lastCapturedSQL!

        // Call the actual GRDB implementation to capture its query
        grdbCapturingQueue.clearCapturedSQL()
        _ = bookmarkDataManager.bookmarksGRDB(forEpisode: "episode-uuid", sorted: .timestamp, grdbQueue: grdbCapturingQueue)
        let grdbSQL = grdbCapturingQueue.lastCapturedSQL!

        // Validate both SQL structure and execution plan equivalence
        assertSQLEquivalent(capturedSQL, grdbSQL)
        try assertExecutionPlanEquivalent(capturedSQL, grdbSQL)
    }

    // MARK: - Bookmarks For Podcast Query Tests

    func testBookmarksForPodcastQuery() throws {
        // Call the SQL implementation to capture the query
        _ = bookmarkDataManager.bookmarks(forPodcast: "podcast-uuid")
        let capturedSQL = sqlCapturingQueue.lastCapturedSQL!

        // Call the actual GRDB implementation to capture its query
        grdbCapturingQueue.clearCapturedSQL()
        _ = bookmarkDataManager.bookmarksGRDB(forPodcast: "podcast-uuid", grdbQueue: grdbCapturingQueue)
        let grdbSQL = grdbCapturingQueue.lastCapturedSQL!

        // Validate both SQL structure and execution plan equivalence
        assertSQLEquivalent(capturedSQL, grdbSQL)
        try assertExecutionPlanEquivalent(capturedSQL, grdbSQL)
    }

    func testBookmarksForPodcastAndEpisodeQuery() throws {
        // Call the SQL implementation to capture the query
        _ = bookmarkDataManager.bookmarks(forPodcast: "podcast-uuid", episodeUuid: "episode-uuid")
        let capturedSQL = sqlCapturingQueue.lastCapturedSQL!

        // Call the actual GRDB implementation to capture its query
        grdbCapturingQueue.clearCapturedSQL()
        _ = bookmarkDataManager.bookmarksGRDB(forPodcast: "podcast-uuid", episodeUuid: "episode-uuid", grdbQueue: grdbCapturingQueue)
        let grdbSQL = grdbCapturingQueue.lastCapturedSQL!

        // Validate both SQL structure and execution plan equivalence
        assertSQLEquivalent(capturedSQL, grdbSQL)
        try assertExecutionPlanEquivalent(capturedSQL, grdbSQL)
    }

    // MARK: - All Bookmarks Query Tests

    func testAllBookmarksExcludeDeletedQuery() throws {
        // Call the SQL implementation to capture the query
        _ = bookmarkDataManager.allBookmarks(includeDeleted: false)
        let capturedSQL = sqlCapturingQueue.lastCapturedSQL!

        // Call the actual GRDB implementation to capture its query
        grdbCapturingQueue.clearCapturedSQL()
        _ = bookmarkDataManager.allBookmarksGRDB(includeDeleted: false, grdbQueue: grdbCapturingQueue)
        let grdbSQL = grdbCapturingQueue.lastCapturedSQL!

        // Validate both SQL structure and execution plan equivalence
        assertSQLEquivalent(capturedSQL, grdbSQL)
        try assertExecutionPlanEquivalent(capturedSQL, grdbSQL)
    }

    func testAllBookmarksIncludeDeletedQuery() throws {
        // Call the SQL implementation to capture the query
        _ = bookmarkDataManager.allBookmarks(includeDeleted: true)
        let capturedSQL = sqlCapturingQueue.lastCapturedSQL!

        // Call the actual GRDB implementation to capture its query
        grdbCapturingQueue.clearCapturedSQL()
        _ = bookmarkDataManager.allBookmarksGRDB(includeDeleted: true, grdbQueue: grdbCapturingQueue)
        let grdbSQL = grdbCapturingQueue.lastCapturedSQL!

        // Validate both SQL structure and execution plan equivalence
        assertSQLEquivalent(capturedSQL, grdbSQL)
        try assertExecutionPlanEquivalent(capturedSQL, grdbSQL)
    }

    // MARK: - Bookmark Count Query Tests

    func testBookmarkCountForEpisodeExcludeDeletedQuery() throws {
        // Call the SQL implementation to capture the query
        _ = bookmarkDataManager.bookmarkCount(forEpisode: "episode-uuid", includeDeleted: false)
        let capturedSQL = sqlCapturingQueue.lastCapturedSQL!

        // Call the actual GRDB implementation to capture its query
        grdbCapturingQueue.clearCapturedSQL()
        _ = bookmarkDataManager.bookmarkCountGRDB(forEpisode: "episode-uuid", includeDeleted: false, grdbQueue: grdbCapturingQueue)
        let grdbSQL = grdbCapturingQueue.lastCapturedSQL!

        // Validate both SQL structure and execution plan equivalence
        assertSQLEquivalent(capturedSQL, grdbSQL)
        try assertExecutionPlanEquivalent(capturedSQL, grdbSQL)
    }

    func testBookmarkCountForEpisodeIncludeDeletedQuery() throws {
        // Call the SQL implementation to capture the query
        _ = bookmarkDataManager.bookmarkCount(forEpisode: "episode-uuid", includeDeleted: true)
        let capturedSQL = sqlCapturingQueue.lastCapturedSQL!

        // Call the actual GRDB implementation to capture its query
        grdbCapturingQueue.clearCapturedSQL()
        _ = bookmarkDataManager.bookmarkCountGRDB(forEpisode: "episode-uuid", includeDeleted: true, grdbQueue: grdbCapturingQueue)
        let grdbSQL = grdbCapturingQueue.lastCapturedSQL!

        // Validate both SQL structure and execution plan equivalence
        assertSQLEquivalent(capturedSQL, grdbSQL)
        try assertExecutionPlanEquivalent(capturedSQL, grdbSQL)
    }

    // MARK: - Bookmarks To Sync Query Tests

    func testBookmarksToSyncQuery() throws {
        // Call the SQL implementation to capture the query
        _ = bookmarkDataManager.bookmarksToSync()
        let capturedSQL = sqlCapturingQueue.lastCapturedSQL!

        // Call the actual GRDB implementation to capture its query
        grdbCapturingQueue.clearCapturedSQL()
        _ = bookmarkDataManager.bookmarksToSyncGRDB(grdbQueue: grdbCapturingQueue)
        let grdbSQL = grdbCapturingQueue.lastCapturedSQL!

        // Validate both SQL structure and execution plan equivalence
        assertSQLEquivalent(capturedSQL, grdbSQL)
        try assertExecutionPlanEquivalent(capturedSQL, grdbSQL)
    }
}
