import XCTest
import GRDB
@testable import PocketCastsDataModel
@testable import PocketCastsUtils

/// Tests that validate the SQL queries generated by GRDB QueryInterface
/// match the raw SQL queries in the SQL implementation for BookmarkDataManager.
///
/// These tests work by:
/// 1. Calling the SQL implementation method with a capturing database queue
/// 2. Extracting the SQL from the equivalent GRDB QueryInterface request
/// 3. Comparing the two SQL strings to ensure they match
final class BookmarkDataManagerQueryTests: SQLQueryComparisonTestCase {

    // MARK: - Test Setup

    private var bookmarkDataManager: BookmarkDataManager!

    override func setUp() async throws {
        try await super.setUp()
        bookmarkDataManager = BookmarkDataManager(dbQueue: sqlCapturingQueue)

        // Create the schema in GRDB for SQL extraction
        try await grdbQueue.write { db in
            try db.create(table: BookmarkRecord.databaseTableName, ifNotExists: true) { t in
                t.column("uuid", .text).notNull().primaryKey()
                t.column("title", .text).notNull().defaults(to: "")
                t.column("time", .double).notNull().defaults(to: 0)
                t.column("date_added", .double).notNull().defaults(to: 0)
                t.column("title_modified_date", .double)
                t.column("episode_uuid", .text).notNull().defaults(to: "")
                t.column("podcast_uuid", .text)
                t.column("sync_status", .integer).notNull().defaults(to: 0)
                t.column("deleted", .boolean).notNull().defaults(to: false)
                t.column("deleted_modified_date", .double)
            }
        }
    }

    override func tearDown() async throws {
        bookmarkDataManager = nil
        try await super.tearDown()
    }

    // MARK: - Find Bookmark By UUID Query Tests

    func testBookmarkByUuidQueryAllowDeleted() throws {
        // Call the SQL implementation to capture the query
        _ = bookmarkDataManager.bookmark(for: "test-uuid", allowDeleted: true)
        let capturedSQL = sqlCapturingQueue.lastCapturedSQL!
        let capturedValues = sqlCapturingQueue.capturedQueries.last?.values

        // Build the equivalent GRDB query
        // Note: selectBookmarks uses default sort (newestToOldest = date_added DESC) and limit 1
        let grdbRequest = BookmarkRecord
            .filter(BookmarkRecord.Columns.uuid == "test-uuid")
            .order(BookmarkRecord.Columns.date_added.desc)
            .limit(1)
        let grdbSQL = try extractSQL(grdbRequest)

        // GRDB parameterizes the uuid
        let grdbValues: [Any] = ["test-uuid"]

        // Compare the SQL
        assertSQLEquivalent(capturedSQL, grdbSQL)
    }

    func testBookmarkByUuidQueryExcludeDeleted() throws {
        // Call the SQL implementation to capture the query
        _ = bookmarkDataManager.bookmark(for: "test-uuid", allowDeleted: false)
        let capturedSQL = sqlCapturingQueue.lastCapturedSQL!
        let capturedValues = sqlCapturingQueue.capturedQueries.last?.values

        // Build the equivalent GRDB query
        // Note: selectBookmarks uses default sort (newestToOldest = date_added DESC) and limit 1
        let grdbRequest = BookmarkRecord
            .filter(BookmarkRecord.Columns.uuid == "test-uuid")
            .filter(BookmarkRecord.Columns.deleted == false)
            .order(BookmarkRecord.Columns.date_added.desc)
            .limit(1)
        let grdbSQL = try extractSQL(grdbRequest)

        // GRDB parameterizes both uuid and deleted
        let grdbValues: [Any] = ["test-uuid", false]

        // Compare the SQL
        assertSQLEquivalent(capturedSQL, grdbSQL)
    }

    // MARK: - Existing Bookmark Query Tests

    func testExistingBookmarkQuery() throws {
        // Call the SQL implementation to capture the query
        _ = bookmarkDataManager.existingBookmark(forEpisode: "episode-uuid", time: 120.5)
        let capturedSQL = sqlCapturingQueue.lastCapturedSQL!
        let capturedValues = sqlCapturingQueue.capturedQueries.last?.values

        // Build the equivalent GRDB query
        // Note: selectBookmarks uses default sort (newestToOldest = date_added DESC) and limit 1
        let grdbRequest = BookmarkRecord
            .filter(BookmarkRecord.Columns.episode_uuid == "episode-uuid")
            .filter(BookmarkRecord.Columns.time == 120.5)
            .filter(BookmarkRecord.Columns.deleted == false)
            .order(BookmarkRecord.Columns.date_added.desc)
            .limit(1)
        let grdbSQL = try extractSQL(grdbRequest)

        // GRDB parameterizes episode_uuid, time, and deleted
        let grdbValues: [Any] = ["episode-uuid", 120.5, false]

        // Compare the SQL
        assertSQLEquivalent(capturedSQL, grdbSQL)
    }

    // MARK: - Bookmarks For Episode Query Tests

    func testBookmarksForEpisodeNewestToOldestQuery() throws {
        // Call the SQL implementation to capture the query
        _ = bookmarkDataManager.bookmarks(forEpisode: "episode-uuid", sorted: .newestToOldest)
        let capturedSQL = sqlCapturingQueue.lastCapturedSQL!
        let capturedValues = sqlCapturingQueue.capturedQueries.last?.values

        // Build the equivalent GRDB query
        let grdbRequest = BookmarkRecord
            .filter(BookmarkRecord.Columns.episode_uuid == "episode-uuid")
            .filter(BookmarkRecord.Columns.deleted == false)
            .order(BookmarkRecord.Columns.date_added.desc)
        let grdbSQL = try extractSQL(grdbRequest)

        // GRDB parameterizes episode_uuid and deleted
        let grdbValues: [Any] = ["episode-uuid", false]

        // Compare the SQL
        assertSQLEquivalent(capturedSQL, grdbSQL)
    }

    func testBookmarksForEpisodeOldestToNewestQuery() throws {
        // Call the SQL implementation to capture the query
        _ = bookmarkDataManager.bookmarks(forEpisode: "episode-uuid", sorted: .oldestToNewest)
        let capturedSQL = sqlCapturingQueue.lastCapturedSQL!
        let capturedValues = sqlCapturingQueue.capturedQueries.last?.values

        // Build the equivalent GRDB query
        let grdbRequest = BookmarkRecord
            .filter(BookmarkRecord.Columns.episode_uuid == "episode-uuid")
            .filter(BookmarkRecord.Columns.deleted == false)
            .order(BookmarkRecord.Columns.date_added.asc)
        let grdbSQL = try extractSQL(grdbRequest)

        // GRDB parameterizes episode_uuid and deleted
        let grdbValues: [Any] = ["episode-uuid", false]

        // Compare the SQL
        assertSQLEquivalent(capturedSQL, grdbSQL)
    }

    func testBookmarksForEpisodeByTimestampQuery() throws {
        // Call the SQL implementation to capture the query
        _ = bookmarkDataManager.bookmarks(forEpisode: "episode-uuid", sorted: .timestamp)
        let capturedSQL = sqlCapturingQueue.lastCapturedSQL!
        let capturedValues = sqlCapturingQueue.capturedQueries.last?.values

        // Build the equivalent GRDB query
        let grdbRequest = BookmarkRecord
            .filter(BookmarkRecord.Columns.episode_uuid == "episode-uuid")
            .filter(BookmarkRecord.Columns.deleted == false)
            .order(BookmarkRecord.Columns.time.asc)
        let grdbSQL = try extractSQL(grdbRequest)

        // GRDB parameterizes episode_uuid and deleted
        let grdbValues: [Any] = ["episode-uuid", false]

        // Compare the SQL
        assertSQLEquivalent(capturedSQL, grdbSQL)
    }

    // MARK: - Bookmarks For Podcast Query Tests

    func testBookmarksForPodcastQuery() throws {
        // Call the SQL implementation to capture the query
        _ = bookmarkDataManager.bookmarks(forPodcast: "podcast-uuid")
        let capturedSQL = sqlCapturingQueue.lastCapturedSQL!
        let capturedValues = sqlCapturingQueue.capturedQueries.last?.values

        // Build the equivalent GRDB query
        let grdbRequest = BookmarkRecord
            .filter(BookmarkRecord.Columns.podcast_uuid == "podcast-uuid")
            .filter(BookmarkRecord.Columns.deleted == false)
            .order(BookmarkRecord.Columns.date_added.desc)
        let grdbSQL = try extractSQL(grdbRequest)

        // GRDB parameterizes podcast_uuid and deleted
        let grdbValues: [Any] = ["podcast-uuid", false]

        // Compare the SQL
        assertSQLEquivalent(capturedSQL, grdbSQL)
    }

    func testBookmarksForPodcastAndEpisodeQuery() throws {
        // Call the SQL implementation to capture the query
        _ = bookmarkDataManager.bookmarks(forPodcast: "podcast-uuid", episodeUuid: "episode-uuid")
        let capturedSQL = sqlCapturingQueue.lastCapturedSQL!
        let capturedValues = sqlCapturingQueue.capturedQueries.last?.values

        // Build the equivalent GRDB query
        let grdbRequest = BookmarkRecord
            .filter(BookmarkRecord.Columns.podcast_uuid == "podcast-uuid")
            .filter(BookmarkRecord.Columns.episode_uuid == "episode-uuid")
            .filter(BookmarkRecord.Columns.deleted == false)
            .order(BookmarkRecord.Columns.date_added.desc)
        let grdbSQL = try extractSQL(grdbRequest)

        // GRDB parameterizes podcast_uuid, episode_uuid, and deleted
        let grdbValues: [Any] = ["podcast-uuid", "episode-uuid", false]

        // Compare the SQL
        assertSQLEquivalent(capturedSQL, grdbSQL)
    }

    // MARK: - All Bookmarks Query Tests

    func testAllBookmarksExcludeDeletedQuery() throws {
        // Call the SQL implementation to capture the query
        _ = bookmarkDataManager.allBookmarks(includeDeleted: false)
        let capturedSQL = sqlCapturingQueue.lastCapturedSQL!
        let capturedValues = sqlCapturingQueue.capturedQueries.last?.values

        // Build the equivalent GRDB query
        let grdbRequest = BookmarkRecord
            .filter(BookmarkRecord.Columns.deleted == false)
            .order(BookmarkRecord.Columns.date_added.desc)
        let grdbSQL = try extractSQL(grdbRequest)

        // GRDB parameterizes deleted
        let grdbValues: [Any] = [false]

        // Compare the SQL
        assertSQLEquivalent(capturedSQL, grdbSQL)
    }

    func testAllBookmarksIncludeDeletedQuery() throws {
        // Call the SQL implementation to capture the query
        _ = bookmarkDataManager.allBookmarks(includeDeleted: true)
        let capturedSQL = sqlCapturingQueue.lastCapturedSQL!
        let capturedValues = sqlCapturingQueue.capturedQueries.last?.values

        // Build the equivalent GRDB query
        let grdbRequest = BookmarkRecord
            .order(BookmarkRecord.Columns.date_added.desc)
        let grdbSQL = try extractSQL(grdbRequest)

        // No GRDB values
        let grdbValues: [Any] = []

        // Compare the SQL
        assertSQLEquivalent(capturedSQL, grdbSQL)
    }

    // MARK: - Bookmark Count Query Tests

    func testBookmarkCountForEpisodeExcludeDeletedQuery() throws {
        // Call the SQL implementation to capture the query
        _ = bookmarkDataManager.bookmarkCount(forEpisode: "episode-uuid", includeDeleted: false)
        let capturedSQL = sqlCapturingQueue.lastCapturedSQL!
        let capturedValues = sqlCapturingQueue.capturedQueries.last?.values

        // Build the equivalent GRDB query (for count, we use the filter part)
        let grdbRequest = BookmarkRecord
            .filter(BookmarkRecord.Columns.episode_uuid == "episode-uuid")
            .filter(BookmarkRecord.Columns.deleted == false)
        let grdbSQL = try extractSQL(grdbRequest)

        // GRDB parameterizes episode_uuid and deleted
        let grdbValues: [Any] = ["episode-uuid", false]

        // Compare the SQL (note: SQL uses COUNT(*), GRDB uses fetchCount internally)
        assertSQLEquivalent(capturedSQL, grdbSQL)
    }

    func testBookmarkCountForEpisodeIncludeDeletedQuery() throws {
        // Call the SQL implementation to capture the query
        _ = bookmarkDataManager.bookmarkCount(forEpisode: "episode-uuid", includeDeleted: true)
        let capturedSQL = sqlCapturingQueue.lastCapturedSQL!
        let capturedValues = sqlCapturingQueue.capturedQueries.last?.values

        // Build the equivalent GRDB query
        let grdbRequest = BookmarkRecord
            .filter(BookmarkRecord.Columns.episode_uuid == "episode-uuid")
        let grdbSQL = try extractSQL(grdbRequest)

        // GRDB parameterizes episode_uuid
        let grdbValues: [Any] = ["episode-uuid"]

        // Compare the SQL
        assertSQLEquivalent(capturedSQL, grdbSQL)
    }

    // MARK: - Bookmarks To Sync Query Tests

    func testBookmarksToSyncQuery() throws {
        // Call the SQL implementation to capture the query
        _ = bookmarkDataManager.bookmarksToSync()
        let capturedSQL = sqlCapturingQueue.lastCapturedSQL!
        let capturedValues = sqlCapturingQueue.capturedQueries.last?.values

        // Build the equivalent GRDB query
        // Note: selectBookmarks uses default sort (newestToOldest = date_added DESC) and allowDeleted: true
        let grdbRequest = BookmarkRecord
            .filter(BookmarkRecord.Columns.sync_status == SyncStatus.notSynced.rawValue)
            .order(BookmarkRecord.Columns.date_added.desc)
        let grdbSQL = try extractSQL(grdbRequest)

        // GRDB parameterizes sync_status
        let grdbValues: [Any] = [SyncStatus.notSynced.rawValue]

        // Compare the SQL
        assertSQLEquivalent(capturedSQL, grdbSQL)
    }
}
