import XCTest
import GRDB
@testable import PocketCastsDataModel
@testable import PocketCastsUtils

/// Tests that validate the SQL queries generated by GRDB QueryInterface
/// match the raw SQL queries in the SQL implementation for BookmarkDataManager.
///
/// These tests work by:
/// 1. Calling the SQL implementation method with a capturing database queue
/// 2. Extracting the SQL from the equivalent GRDB QueryInterface request
/// 3. Comparing both:
///    - SQL structure (after normalization) to catch structural differences
///    - Execution plans (via EXPLAIN QUERY PLAN) to ensure SQLite treats them equivalently
///
/// This dual approach validates both that the queries are structurally equivalent
/// and that any superficial differences (like clause ordering) don't affect performance.
final class BookmarkDataManagerQueryTests: SQLQueryComparisonTestCase {

    // MARK: - Test Setup

    private var bookmarkDataManager: BookmarkDataManager!

    override func setUp() async throws {
        try await super.setUp()
        bookmarkDataManager = BookmarkDataManager(dbQueue: sqlCapturingQueue)

        // Create the schema in GRDB for SQL extraction
        try await grdbQueue.write { db in
            try db.create(table: Bookmark.databaseTableName, ifNotExists: true) { t in
                t.column("uuid", .text).notNull().primaryKey()
                t.column("title", .text).notNull().defaults(to: "")
                t.column("time", .double).notNull().defaults(to: 0)
                t.column("date_added", .double).notNull().defaults(to: 0)
                t.column("title_modified_date", .double)
                t.column("episode_uuid", .text).notNull().defaults(to: "")
                t.column("podcast_uuid", .text)
                t.column("sync_status", .integer).notNull().defaults(to: 0)
                t.column("deleted", .boolean).notNull().defaults(to: false)
                t.column("deleted_modified_date", .double)
            }
        }
    }

    override func tearDown() async throws {
        bookmarkDataManager = nil
        try await super.tearDown()
    }

    // MARK: - Find Bookmark By UUID Query Tests

    func testBookmarkByUuidQueryAllowDeleted() throws {
        // Call the SQL implementation to capture the query
        _ = bookmarkDataManager.bookmark(for: "test-uuid", allowDeleted: true)
        let capturedSQL = sqlCapturingQueue.lastCapturedSQL!

        // Build the equivalent GRDB query
        // Note: selectBookmarks uses default sort (newestToOldest = date_added DESC) and limit 1
        let grdbRequest = Bookmark
            .filter(Bookmark.Columns.uuid == "test-uuid")
            .order(Bookmark.Columns.created.desc)
            .limit(1)
        let grdbSQL = try extractSQL(grdbRequest)

        // Validate both SQL structure and execution plan equivalence
        assertSQLEquivalent(capturedSQL, grdbSQL)
        try assertExecutionPlanEquivalent(capturedSQL, grdbSQL)
    }

    func testBookmarkByUuidQueryExcludeDeleted() throws {
        // Call the SQL implementation to capture the query
        _ = bookmarkDataManager.bookmark(for: "test-uuid", allowDeleted: false)
        let capturedSQL = sqlCapturingQueue.lastCapturedSQL!

        // Build the equivalent GRDB query
        // Note: selectBookmarks uses default sort (newestToOldest = date_added DESC) and limit 1
        let grdbRequest = Bookmark
            .filter(Bookmark.Columns.uuid == "test-uuid")
            .filter(Bookmark.Columns.deleted == false)
            .order(Bookmark.Columns.created.desc)
            .limit(1)
        let grdbSQL = try extractSQL(grdbRequest)

        // Validate both SQL structure and execution plan equivalence
        assertSQLEquivalent(capturedSQL, grdbSQL)
        try assertExecutionPlanEquivalent(capturedSQL, grdbSQL)
    }

    // MARK: - Existing Bookmark Query Tests

    func testExistingBookmarkQuery() throws {
        // Call the SQL implementation to capture the query
        _ = bookmarkDataManager.existingBookmark(forEpisode: "episode-uuid", time: 120.5)
        let capturedSQL = sqlCapturingQueue.lastCapturedSQL!

        // Build the equivalent GRDB query
        // Note: selectBookmarks uses default sort (newestToOldest = date_added DESC) and limit 1
        let grdbRequest = Bookmark
            .filter(Bookmark.Columns.episodeUuid == "episode-uuid")
            .filter(Bookmark.Columns.time == 120.5)
            .filter(Bookmark.Columns.deleted == false)
            .order(Bookmark.Columns.created.desc)
            .limit(1)
        let grdbSQL = try extractSQL(grdbRequest)

        // Validate both SQL structure and execution plan equivalence
        assertSQLEquivalent(capturedSQL, grdbSQL)
        try assertExecutionPlanEquivalent(capturedSQL, grdbSQL)
    }

    // MARK: - Bookmarks For Episode Query Tests

    func testBookmarksForEpisodeNewestToOldestQuery() throws {
        // Call the SQL implementation to capture the query
        _ = bookmarkDataManager.bookmarks(forEpisode: "episode-uuid", sorted: .newestToOldest)
        let capturedSQL = sqlCapturingQueue.lastCapturedSQL!

        // Build the equivalent GRDB query
        let grdbRequest = Bookmark
            .filter(Bookmark.Columns.episodeUuid == "episode-uuid")
            .filter(Bookmark.Columns.deleted == false)
            .order(Bookmark.Columns.created.desc)
        let grdbSQL = try extractSQL(grdbRequest)

        // Validate both SQL structure and execution plan equivalence
        assertSQLEquivalent(capturedSQL, grdbSQL)
        try assertExecutionPlanEquivalent(capturedSQL, grdbSQL)
    }

    func testBookmarksForEpisodeOldestToNewestQuery() throws {
        // Call the SQL implementation to capture the query
        _ = bookmarkDataManager.bookmarks(forEpisode: "episode-uuid", sorted: .oldestToNewest)
        let capturedSQL = sqlCapturingQueue.lastCapturedSQL!

        // Build the equivalent GRDB query
        let grdbRequest = Bookmark
            .filter(Bookmark.Columns.episodeUuid == "episode-uuid")
            .filter(Bookmark.Columns.deleted == false)
            .order(Bookmark.Columns.created.asc)
        let grdbSQL = try extractSQL(grdbRequest)

        // Validate both SQL structure and execution plan equivalence
        assertSQLEquivalent(capturedSQL, grdbSQL)
        try assertExecutionPlanEquivalent(capturedSQL, grdbSQL)
    }

    func testBookmarksForEpisodeByTimestampQuery() throws {
        // Call the SQL implementation to capture the query
        _ = bookmarkDataManager.bookmarks(forEpisode: "episode-uuid", sorted: .timestamp)
        let capturedSQL = sqlCapturingQueue.lastCapturedSQL!

        // Build the equivalent GRDB query
        let grdbRequest = Bookmark
            .filter(Bookmark.Columns.episodeUuid == "episode-uuid")
            .filter(Bookmark.Columns.deleted == false)
            .order(Bookmark.Columns.time.asc)
        let grdbSQL = try extractSQL(grdbRequest)

        // Validate both SQL structure and execution plan equivalence
        assertSQLEquivalent(capturedSQL, grdbSQL)
        try assertExecutionPlanEquivalent(capturedSQL, grdbSQL)
    }

    // MARK: - Bookmarks For Podcast Query Tests

    func testBookmarksForPodcastQuery() throws {
        // Call the SQL implementation to capture the query
        _ = bookmarkDataManager.bookmarks(forPodcast: "podcast-uuid")
        let capturedSQL = sqlCapturingQueue.lastCapturedSQL!

        // Build the equivalent GRDB query
        let grdbRequest = Bookmark
            .filter(Bookmark.Columns.podcastUuid == "podcast-uuid")
            .filter(Bookmark.Columns.deleted == false)
            .order(Bookmark.Columns.created.desc)
        let grdbSQL = try extractSQL(grdbRequest)

        // Validate both SQL structure and execution plan equivalence
        assertSQLEquivalent(capturedSQL, grdbSQL)
        try assertExecutionPlanEquivalent(capturedSQL, grdbSQL)
    }

    func testBookmarksForPodcastAndEpisodeQuery() throws {
        // Call the SQL implementation to capture the query
        _ = bookmarkDataManager.bookmarks(forPodcast: "podcast-uuid", episodeUuid: "episode-uuid")
        let capturedSQL = sqlCapturingQueue.lastCapturedSQL!

        // Build the equivalent GRDB query
        let grdbRequest = Bookmark
            .filter(Bookmark.Columns.podcastUuid == "podcast-uuid")
            .filter(Bookmark.Columns.episodeUuid == "episode-uuid")
            .filter(Bookmark.Columns.deleted == false)
            .order(Bookmark.Columns.created.desc)
        let grdbSQL = try extractSQL(grdbRequest)

        // Validate both SQL structure and execution plan equivalence
        assertSQLEquivalent(capturedSQL, grdbSQL)
        try assertExecutionPlanEquivalent(capturedSQL, grdbSQL)
    }

    // MARK: - All Bookmarks Query Tests

    func testAllBookmarksExcludeDeletedQuery() throws {
        // Call the SQL implementation to capture the query
        _ = bookmarkDataManager.allBookmarks(includeDeleted: false)
        let capturedSQL = sqlCapturingQueue.lastCapturedSQL!

        // Build the equivalent GRDB query
        let grdbRequest = Bookmark
            .filter(Bookmark.Columns.deleted == false)
            .order(Bookmark.Columns.created.desc)
        let grdbSQL = try extractSQL(grdbRequest)

        // Validate both SQL structure and execution plan equivalence
        assertSQLEquivalent(capturedSQL, grdbSQL)
        try assertExecutionPlanEquivalent(capturedSQL, grdbSQL)
    }

    func testAllBookmarksIncludeDeletedQuery() throws {
        // Call the SQL implementation to capture the query
        _ = bookmarkDataManager.allBookmarks(includeDeleted: true)
        let capturedSQL = sqlCapturingQueue.lastCapturedSQL!

        // Build the equivalent GRDB query
        let grdbRequest = Bookmark
            .order(Bookmark.Columns.created.desc)
        let grdbSQL = try extractSQL(grdbRequest)

        // Validate both SQL structure and execution plan equivalence
        assertSQLEquivalent(capturedSQL, grdbSQL)
        try assertExecutionPlanEquivalent(capturedSQL, grdbSQL)
    }

    // MARK: - Bookmark Count Query Tests

    func testBookmarkCountForEpisodeExcludeDeletedQuery() throws {
        // Call the SQL implementation to capture the query
        _ = bookmarkDataManager.bookmarkCount(forEpisode: "episode-uuid", includeDeleted: false)
        let capturedSQL = sqlCapturingQueue.lastCapturedSQL!

        // Build the equivalent GRDB query (for count, we use extractCountSQL)
        let grdbRequest = Bookmark
            .filter(Bookmark.Columns.episodeUuid == "episode-uuid")
            .filter(Bookmark.Columns.deleted == false)
        let grdbSQL = try extractCountSQL(grdbRequest)

        // Validate both SQL structure and execution plan equivalence
        assertSQLEquivalent(capturedSQL, grdbSQL)
        try assertExecutionPlanEquivalent(capturedSQL, grdbSQL)
    }

    func testBookmarkCountForEpisodeIncludeDeletedQuery() throws {
        // Call the SQL implementation to capture the query
        _ = bookmarkDataManager.bookmarkCount(forEpisode: "episode-uuid", includeDeleted: true)
        let capturedSQL = sqlCapturingQueue.lastCapturedSQL!

        // Build the equivalent GRDB query (for count, we use extractCountSQL)
        let grdbRequest = Bookmark
            .filter(Bookmark.Columns.episodeUuid == "episode-uuid")
        let grdbSQL = try extractCountSQL(grdbRequest)

        // Validate both SQL structure and execution plan equivalence
        assertSQLEquivalent(capturedSQL, grdbSQL)
        try assertExecutionPlanEquivalent(capturedSQL, grdbSQL)
    }

    // MARK: - Bookmarks To Sync Query Tests

    func testBookmarksToSyncQuery() throws {
        // Call the SQL implementation to capture the query
        _ = bookmarkDataManager.bookmarksToSync()
        let capturedSQL = sqlCapturingQueue.lastCapturedSQL!

        // Build the equivalent GRDB query
        // Note: selectBookmarks uses default sort (newestToOldest = date_added DESC) and allowDeleted: true
        let grdbRequest = Bookmark
            .filter(Bookmark.Columns.syncStatus == SyncStatus.notSynced.rawValue)
            .order(Bookmark.Columns.created.desc)
        let grdbSQL = try extractSQL(grdbRequest)

        // Validate both SQL structure and execution plan equivalence
        assertSQLEquivalent(capturedSQL, grdbSQL)
        try assertExecutionPlanEquivalent(capturedSQL, grdbSQL)
    }
}
