import XCTest
import GRDB
@testable import PocketCastsDataModel
@testable import PocketCastsUtils

/// Tests that validate the SQL queries generated by GRDB QueryInterface
/// match the raw SQL queries in the SQL implementation for EpisodeDataManager.
///
/// These tests work by:
/// 1. Calling the SQL implementation method with a capturing database queue
/// 2. Extracting the SQL from the equivalent GRDB QueryInterface request
/// 3. Comparing the two SQL strings to ensure they match
final class EpisodeDataManagerQueryTests: SQLQueryComparisonTestCase {

    // MARK: - Test Setup

    private var episodeDataManager: EpisodeDataManager!

    override func setUp() async throws {
        try await super.setUp()
        episodeDataManager = EpisodeDataManager()

        // Create the schema in GRDB for SQL extraction
        try await grdbQueue.write { db in
            try db.create(table: EpisodeRecord.databaseTableName, ifNotExists: true) { t in
                t.autoIncrementedPrimaryKey("id")
                t.column("addedDate", .double)
                t.column("lastDownloadAttemptDate", .double)
                t.column("detailedDescription", .text)
                t.column("downloadErrorDetails", .text)
                t.column("downloadTaskId", .text)
                t.column("downloadUrl", .text)
                t.column("episodeDescription", .text)
                t.column("episodeStatus", .integer).notNull().defaults(to: 0)
                t.column("fileType", .text)
                t.column("contentType", .text)
                t.column("keepEpisode", .boolean).notNull().defaults(to: false)
                t.column("playedUpTo", .double).notNull().defaults(to: 0)
                t.column("duration", .double).notNull().defaults(to: 0)
                t.column("playingStatus", .integer).notNull().defaults(to: 0)
                t.column("autoDownloadStatus", .integer).notNull().defaults(to: 0)
                t.column("publishedDate", .double)
                t.column("sizeInBytes", .integer).notNull().defaults(to: 0)
                t.column("playingStatusModified", .integer).notNull().defaults(to: 0)
                t.column("playedUpToModified", .integer).notNull().defaults(to: 0)
                t.column("durationModified", .integer).notNull().defaults(to: 0)
                t.column("keepEpisodeModified", .integer).notNull().defaults(to: 0)
                t.column("title", .text)
                t.column("uuid", .text).notNull().defaults(to: "")
                t.column("podcastUuid", .text).notNull().defaults(to: "")
                t.column("playbackErrorDetails", .text)
                t.column("cachedFrameCount", .integer).notNull().defaults(to: 0)
                t.column("lastPlaybackInteractionDate", .double)
                t.column("lastPlaybackInteractionSyncStatus", .integer).notNull().defaults(to: 1)
                t.column("podcast_id", .integer).notNull().defaults(to: 0)
                t.column("episodeNumber", .integer).notNull().defaults(to: -1)
                t.column("seasonNumber", .integer).notNull().defaults(to: -1)
                t.column("episodeType", .text)
                t.column("archived", .boolean).notNull().defaults(to: false)
                t.column("archivedModified", .integer).notNull().defaults(to: 0)
                t.column("lastArchiveInteractionDate", .double)
                t.column("excludeFromEpisodeLimit", .boolean).notNull().defaults(to: false)
                t.column("starredModified", .integer).notNull().defaults(to: 0)
                t.column("deselectedChapters", .text)
                t.column("deselectedChaptersModified", .integer).notNull().defaults(to: 0)
                t.column("wasDeleted", .boolean).notNull().defaults(to: false)
                t.column("metadata", .text)
            }
        }
    }

    override func tearDown() async throws {
        episodeDataManager = nil
        try await super.tearDown()
    }

    // MARK: - Find By UUID Query Tests

    func testFindByUuidQuery() throws {
        // Call the SQL implementation to capture the query
        _ = episodeDataManager.findBy(uuid: "test-uuid", dbQueue: sqlCapturingQueue)
        let capturedSQL = sqlCapturingQueue.lastCapturedSQL!
        let capturedValues = sqlCapturingQueue.capturedQueries.last?.values

        // Build the equivalent GRDB query
        let grdbRequest = EpisodeRecord
            .filter(EpisodeRecord.Columns.uuid == "test-uuid")
        let grdbSQL = try extractSQL(grdbRequest)

        // Compare the SQL (both have ? placeholders, use same values for substitution)
        assertSQLEquivalent(capturedSQL, grdbSQL)
    }

    // MARK: - Find By Download Task ID Query Tests

    func testFindByDownloadTaskIdQuery() throws {
        // Call the SQL implementation to capture the query
        _ = episodeDataManager.findBy(downloadTaskId: "task-123", dbQueue: sqlCapturingQueue)
        let capturedSQL = sqlCapturingQueue.lastCapturedSQL!
        let capturedValues = sqlCapturingQueue.capturedQueries.last?.values

        // Build the equivalent GRDB query
        let grdbRequest = EpisodeRecord
            .filter(EpisodeRecord.Columns.downloadTaskId == "task-123")
        let grdbSQL = try extractSQL(grdbRequest)

        // Compare the SQL
        assertSQLEquivalent(capturedSQL, grdbSQL)
    }

    // MARK: - All Episodes For Podcast Query Tests

    func testAllEpisodesForPodcastQuery() throws {
        // Call the SQL implementation to capture the query
        _ = episodeDataManager.allEpisodesForPodcast(id: 123, dbQueue: sqlCapturingQueue)
        let capturedSQL = sqlCapturingQueue.lastCapturedSQL!
        let capturedValues = sqlCapturingQueue.capturedQueries.last?.values

        // Build the equivalent GRDB query
        let grdbRequest = EpisodeRecord
            .filter(EpisodeRecord.Columns.podcast_id == Int64(123))
            .filter(EpisodeRecord.Columns.wasDeleted == false)
        let grdbSQL = try extractSQL(grdbRequest)

        // GRDB has two placeholders: podcast_id and wasDeleted
        // SQL implementation has one placeholder (podcast_id) and hardcodes wasDeleted = 0
        let grdbValues: [Any] = [Int64(123), false]

        // Compare the SQL
        assertSQLEquivalent(capturedSQL, grdbSQL)
    }

    // MARK: - Find Latest Episode Query Tests

    func testFindLatestEpisodeQuery() throws {
        // Create a mock podcast for the test
        let podcast = Podcast()
        podcast.id = 123

        // Call the SQL implementation to capture the query
        _ = episodeDataManager.findLatestEpisode(podcast: podcast, dbQueue: sqlCapturingQueue)
        let capturedSQL = sqlCapturingQueue.lastCapturedSQL!
        let capturedValues = sqlCapturingQueue.capturedQueries.last?.values

        // Build the equivalent GRDB query
        // Note: GRDB's .order() replaces previous orderings, so use a single call with multiple columns
        let grdbRequest = EpisodeRecord
            .filter(EpisodeRecord.Columns.podcast_id == Int64(123))
            .filter(EpisodeRecord.Columns.wasDeleted == false)
            .order(EpisodeRecord.Columns.publishedDate.desc, EpisodeRecord.Columns.addedDate.desc)
            .limit(1)
        let grdbSQL = try extractSQL(grdbRequest)

        // GRDB parameterizes both podcast_id and wasDeleted
        let grdbValues: [Any] = [Int64(123), false]

        // Compare the SQL
        assertSQLEquivalent(capturedSQL, grdbSQL)
    }

    // MARK: - Find Latest Episodes Query Tests

    func testFindLatestEpisodesQuery() throws {
        // Create a mock podcast for the test
        let podcast = Podcast()
        podcast.id = 123

        // Call the SQL implementation to capture the query
        _ = episodeDataManager.findLatestEpisodes(podcast: podcast, limit: 10, dbQueue: sqlCapturingQueue)
        let capturedSQL = sqlCapturingQueue.lastCapturedSQL!
        let capturedValues = sqlCapturingQueue.capturedQueries.last?.values

        // Build the equivalent GRDB query
        // Note: GRDB's .order() replaces previous orderings, so use a single call with multiple columns
        let grdbRequest = EpisodeRecord
            .filter(EpisodeRecord.Columns.podcast_id == Int64(123))
            .filter(EpisodeRecord.Columns.wasDeleted == false)
            .order(EpisodeRecord.Columns.publishedDate.desc, EpisodeRecord.Columns.addedDate.desc)
            .limit(10)
        let grdbSQL = try extractSQL(grdbRequest)

        // GRDB parameterizes both podcast_id and wasDeleted
        let grdbValues: [Any] = [Int64(123), false]

        // Compare the SQL
        assertSQLEquivalent(capturedSQL, grdbSQL)
    }

    // MARK: - Episodes With Listen History Query Tests

    func testEpisodesWithListenHistoryQuery() throws {
        // Call the SQL implementation to capture the query
        _ = episodeDataManager.episodesWithListenHistory(limit: 100, dbQueue: sqlCapturingQueue)
        let capturedSQL = sqlCapturingQueue.lastCapturedSQL!
        let capturedValues = sqlCapturingQueue.capturedQueries.last?.values

        // Build the equivalent GRDB query
        let grdbRequest = EpisodeRecord
            .filter(EpisodeRecord.Columns.lastPlaybackInteractionDate != nil)
            .filter(EpisodeRecord.Columns.lastPlaybackInteractionDate > 0)
            .order(EpisodeRecord.Columns.lastPlaybackInteractionDate.desc)
            .limit(100)
        let grdbSQL = try extractSQL(grdbRequest)

        // GRDB parameterizes the > 0 comparison
        let grdbValues: [Any] = [0]

        // Compare the SQL
        assertSQLEquivalent(capturedSQL, grdbSQL)
    }

    // MARK: - Downloaded Episode Count Query Tests

    func testDownloadedEpisodeCountQuery() throws {
        // Call the SQL implementation to capture the query
        _ = episodeDataManager.downloadedEpisodeCount(dbQueue: sqlCapturingQueue)
        let capturedSQL = sqlCapturingQueue.lastCapturedSQL!
        let capturedValues = sqlCapturingQueue.capturedQueries.last?.values

        // Build the equivalent GRDB query (count queries use the same filter)
        let grdbRequest = EpisodeRecord
            .filter(EpisodeRecord.Columns.episodeStatus == DownloadStatus.downloaded.rawValue)
        let grdbSQL = try extractCountSQL(grdbRequest)

        // GRDB parameterizes the status value
        let grdbValues: [Any] = [DownloadStatus.downloaded.rawValue]

        // Compare the SQL (note: SQL uses COUNT(*), GRDB request is SELECT * but fetchCount uses COUNT)
        assertSQLEquivalent(capturedSQL, grdbSQL)
    }

    // MARK: - Failed Download Episode Count Query Tests

    func testFailedDownloadEpisodeCountQuery() throws {
        // Call the SQL implementation to capture the query
        _ = episodeDataManager.failedDownloadEpisodeCount(dbQueue: sqlCapturingQueue)
        let capturedSQL = sqlCapturingQueue.lastCapturedSQL!
        let capturedValues = sqlCapturingQueue.capturedQueries.last?.values

        // Build the equivalent GRDB query
        let grdbRequest = EpisodeRecord
            .filter(EpisodeRecord.Columns.episodeStatus == DownloadStatus.downloadFailed.rawValue)
        let grdbSQL = try extractCountSQL(grdbRequest)

        // GRDB parameterizes the status value
        let grdbValues: [Any] = [DownloadStatus.downloadFailed.rawValue]

        // Compare the SQL
        assertSQLEquivalent(capturedSQL, grdbSQL)
    }

    // MARK: - Downloaded Episode Exists Query Tests

    func testDownloadedEpisodeExistsQuery() throws {
        // Call the SQL implementation to capture the query
        _ = episodeDataManager.downloadedEpisodeExists(uuid: "test-uuid", dbQueue: sqlCapturingQueue)
        let capturedSQL = sqlCapturingQueue.lastCapturedSQL!
        let capturedValues = sqlCapturingQueue.capturedQueries.last?.values

        // Build the equivalent GRDB query
        let grdbRequest = EpisodeRecord
            .filter(EpisodeRecord.Columns.uuid == "test-uuid")
            .filter(EpisodeRecord.Columns.episodeStatus == DownloadStatus.downloaded.rawValue)
        let grdbSQL = try extractSQL(grdbRequest)

        // GRDB parameterizes both uuid and status
        let grdbValues: [Any] = ["test-uuid", DownloadStatus.downloaded.rawValue]

        // Compare the SQL
        assertSQLEquivalent(capturedSQL, grdbSQL)
    }

    // MARK: - Unsynced Episodes Query Tests

    func testUnsyncedEpisodesQuery() throws {
        // Call the SQL implementation to capture the query
        _ = episodeDataManager.unsyncedEpisodes(limit: 100, dbQueue: sqlCapturingQueue)
        let capturedSQL = sqlCapturingQueue.lastCapturedSQL!
        let capturedValues = sqlCapturingQueue.capturedQueries.last?.values

        // Build the equivalent GRDB query
        let playingStatusFilter = EpisodeRecord.Columns.playingStatusModified > 0
        let playedUpToFilter = EpisodeRecord.Columns.playedUpToModified > 0
        let durationFilter = EpisodeRecord.Columns.durationModified > 0
        let keepEpisodeFilter = EpisodeRecord.Columns.keepEpisodeModified > 0
        let archivedFilter = EpisodeRecord.Columns.archivedModified > 0
        let combinedFilter = playingStatusFilter || playedUpToFilter || durationFilter || keepEpisodeFilter || archivedFilter

        // Note: GRDB's .order() replaces previous orderings, so use a single call with multiple columns
        let grdbRequest = EpisodeRecord
            .filter(combinedFilter)
            .order(EpisodeRecord.Columns.publishedDate.desc, EpisodeRecord.Columns.addedDate.desc)
            .limit(100)
        let grdbSQL = try extractSQL(grdbRequest)

        // GRDB parameterizes all the > 0 comparisons
        let grdbValues: [Any] = [0, 0, 0, 0, 0]

        // Compare the SQL
        assertSQLEquivalent(capturedSQL, grdbSQL)
    }
}
