import XCTest
import GRDB
@testable import PocketCastsDataModel
@testable import PocketCastsUtils

/// Tests that validate the SQL queries generated by GRDB QueryInterface
/// match the raw SQL queries in the SQL implementation for FolderDataManager.
///
/// These tests work by:
/// 1. Calling the SQL implementation method with a capturing database queue
/// 2. Extracting the SQL from the equivalent GRDB QueryInterface request
/// 3. Comparing the two SQL strings to ensure they match
final class FolderDataManagerQueryTests: SQLQueryComparisonTestCase {

    // MARK: - Test Setup

    private var folderDataManager: FolderDataManager!

    override func setUp() async throws {
        try await super.setUp()
        folderDataManager = FolderDataManager()

        // Create the schema in GRDB for SQL extraction
        try await grdbQueue.write { db in
            try db.create(table: FolderRecord.databaseTableName, ifNotExists: true) { t in
                t.column("uuid", .text).notNull().primaryKey()
                t.column("name", .text).notNull().defaults(to: "")
                t.column("color", .integer).notNull().defaults(to: 0)
                t.column("addedDate", .integer).notNull().defaults(to: 0)
                t.column("sortOrder", .integer).notNull().defaults(to: 0)
                t.column("sortType", .integer).notNull().defaults(to: 0)
                t.column("wasDeleted", .boolean).notNull().defaults(to: false)
                t.column("syncModified", .integer).notNull().defaults(to: 0)
            }
        }
    }

    override func tearDown() async throws {
        folderDataManager = nil
        try await super.tearDown()
    }

    // MARK: - Delete Folder Query Tests

    func testDeleteFolderByUuidQuery() throws {
        // Call the SQL implementation to capture the query
        folderDataManager.delete(folderUuid: "folder-uuid", dbQueue: sqlCapturingQueue)

        // Find the DELETE query and expand placeholders
        let deleteQuery = sqlCapturingQueue.capturedQueries.first { $0.sql.uppercased().starts(with: "DELETE") }
        let capturedSQL = sqlCapturingQueue.expandSQL(deleteQuery!.sql, values: deleteQuery?.values)

        // Build the equivalent GRDB query
        let grdbRequest = FolderRecord
            .filter(FolderRecord.Columns.uuid == "folder-uuid")
        let grdbSQL = try extractDeleteSQL(grdbRequest)

        // Compare the SQL
        assertSQLEquivalent(capturedSQL, grdbSQL)
    }

    func testDeleteAllFoldersQuery() throws {
        // Call the SQL implementation to capture the query
        folderDataManager.deleteAllFolders(dbQueue: sqlCapturingQueue)

        // Find the DELETE query
        let deleteQuery = sqlCapturingQueue.capturedQueries.first { $0.sql.uppercased().starts(with: "DELETE") }
        let capturedSQL = deleteQuery!.sql

        // Build the equivalent GRDB query
        let grdbRequest = FolderRecord.all()
        let grdbSQL = try extractDeleteSQL(grdbRequest)

        // Compare the SQL
        assertSQLEquivalent(capturedSQL, grdbSQL)
    }

    // MARK: - Update Folder Color Query Tests

    func testUpdateFolderColorQuery() throws {
        // Call the SQL implementation to capture the query
        folderDataManager.updateFolderColor(folderUuid: "folder-uuid", color: 5, syncModified: 12345, dbQueue: sqlCapturingQueue)

        // Find the UPDATE query and expand placeholders
        let updateQuery = sqlCapturingQueue.capturedQueries.first { $0.sql.uppercased().starts(with: "UPDATE") }
        let capturedSQL = sqlCapturingQueue.expandSQL(updateQuery!.sql, values: updateQuery?.values)

        // Build the equivalent GRDB UPDATE query
        let grdbRequest = FolderRecord
            .filter(FolderRecord.Columns.uuid == "folder-uuid")
        let grdbSQL = try extractUpdateSQL(grdbRequest, assignments: [
            FolderRecord.Columns.color.set(to: 5),
            FolderRecord.Columns.syncModified.set(to: 12345)
        ])

        // Compare the SQL
        assertSQLEquivalent(capturedSQL, grdbSQL)
    }

    // MARK: - Update Folder Sync Modified Query Tests

    func testUpdateFolderSyncModifiedQuery() throws {
        // Call the SQL implementation to capture the query
        folderDataManager.updateFolderSyncModified(folderUuid: "folder-uuid", syncModified: 12345, dbQueue: sqlCapturingQueue)

        // Find the UPDATE query and expand placeholders
        let updateQuery = sqlCapturingQueue.capturedQueries.first { $0.sql.uppercased().starts(with: "UPDATE") }
        let capturedSQL = sqlCapturingQueue.expandSQL(updateQuery!.sql, values: updateQuery?.values)

        // Build the equivalent GRDB UPDATE query
        let grdbRequest = FolderRecord
            .filter(FolderRecord.Columns.uuid == "folder-uuid")
        let grdbSQL = try extractUpdateSQL(grdbRequest, assignments: [
            FolderRecord.Columns.syncModified.set(to: 12345)
        ])

        // Compare the SQL
        assertSQLEquivalent(capturedSQL, grdbSQL)
    }

    // MARK: - Bulk Set Sync Modified Query Tests

    func testBulkSetSyncModifiedQuery() throws {
        let folderUuids = ["uuid-1", "uuid-2", "uuid-3"]

        // Call the SQL implementation to capture the query
        folderDataManager.bulkSetSyncModified(12345, onFolders: folderUuids, dbQueue: sqlCapturingQueue)

        // Find the UPDATE query and expand placeholders
        let updateQuery = sqlCapturingQueue.capturedQueries.first { $0.sql.uppercased().starts(with: "UPDATE") }
        let capturedSQL = sqlCapturingQueue.expandSQL(updateQuery!.sql, values: updateQuery?.values)

        // Build the equivalent GRDB UPDATE query
        let grdbRequest = FolderRecord
            .filter(folderUuids.contains(FolderRecord.Columns.uuid))
        let grdbSQL = try extractUpdateSQL(grdbRequest, assignments: [
            FolderRecord.Columns.syncModified.set(to: 12345)
        ])

        // Compare the SQL
        assertSQLEquivalent(capturedSQL, grdbSQL)
    }

    // MARK: - Mark All Folders Synced Query Tests

    func testMarkAllFoldersSyncedQuery() throws {
        // Call the SQL implementation to capture the query
        folderDataManager.markAllFoldersSynced(dbQueue: sqlCapturingQueue)

        // Find the UPDATE query and expand placeholders
        let updateQuery = sqlCapturingQueue.capturedQueries.first { $0.sql.uppercased().starts(with: "UPDATE") }
        let capturedSQL = sqlCapturingQueue.expandSQL(updateQuery!.sql, values: updateQuery?.values)

        // Build the equivalent GRDB UPDATE query (no WHERE clause)
        let grdbRequest = FolderRecord.all()
        let grdbSQL = try extractUpdateSQL(grdbRequest, assignments: [
            FolderRecord.Columns.syncModified.set(to: 0)
        ])

        // Compare the SQL
        assertSQLEquivalent(capturedSQL, grdbSQL)
    }

    // MARK: - Mark Folder As Deleted Query Tests

    func testMarkFolderAsDeletedQuery() throws {
        // Call the SQL implementation to capture the query
        folderDataManager.markFolderAsDeleted(folderUuid: "folder-uuid", syncModified: 12345, dbQueue: sqlCapturingQueue)

        // Find the UPDATE query and expand placeholders
        let updateQuery = sqlCapturingQueue.capturedQueries.first { $0.sql.uppercased().starts(with: "UPDATE") }
        let capturedSQL = sqlCapturingQueue.expandSQL(updateQuery!.sql, values: updateQuery?.values)

        // Build the equivalent GRDB UPDATE query
        let grdbRequest = FolderRecord
            .filter(FolderRecord.Columns.uuid == "folder-uuid")
        let grdbSQL = try extractUpdateSQL(grdbRequest, assignments: [
            FolderRecord.Columns.syncModified.set(to: 12345),
            FolderRecord.Columns.wasDeleted.set(to: true)
        ])

        // Compare the SQL
        assertSQLEquivalent(capturedSQL, grdbSQL)
    }

    // MARK: - Mark All Folders As Deleted Query Tests

    func testMarkAllFoldersAsDeletedQuery() throws {
        // Call the SQL implementation to capture the query
        folderDataManager.markAllFolderAsDeleted(syncModified: 12345, dbQueue: sqlCapturingQueue)

        // Find the UPDATE query and expand placeholders
        let updateQuery = sqlCapturingQueue.capturedQueries.first { $0.sql.uppercased().starts(with: "UPDATE") }
        let capturedSQL = sqlCapturingQueue.expandSQL(updateQuery!.sql, values: updateQuery?.values)

        // Build the equivalent GRDB UPDATE query (no WHERE clause)
        let grdbRequest = FolderRecord.all()
        let grdbSQL = try extractUpdateSQL(grdbRequest, assignments: [
            FolderRecord.Columns.syncModified.set(to: 12345),
            FolderRecord.Columns.wasDeleted.set(to: true)
        ])

        // Compare the SQL
        assertSQLEquivalent(capturedSQL, grdbSQL)
    }
}
