import XCTest
import GRDB
@testable import PocketCastsDataModel
@testable import PocketCastsUtils

/// Tests that validate the SQL queries generated by GRDB QueryInterface
/// match the raw SQL queries in the SQL implementation for PlaylistDataManager.
///
/// These tests work by:
/// 1. Calling the SQL implementation method with a capturing database queue
/// 2. Extracting the SQL from the equivalent GRDB QueryInterface request
/// 3. Comparing the two SQL strings to ensure they match
final class PlaylistDataManagerQueryTests: SQLQueryComparisonTestCase {

    // MARK: - Test Setup

    private var playlistDataManager: PlaylistDataManager!

    override func setUp() async throws {
        try await super.setUp()
        playlistDataManager = PlaylistDataManager()

        // Create the schema in GRDB for SQL extraction
        try await grdbQueue.write { db in
            try db.create(table: PlaylistRecord.databaseTableName, ifNotExists: true) { t in
                t.autoIncrementedPrimaryKey("id")
                t.column("autoDownloadEpisodes", .boolean).notNull().defaults(to: false)
                t.column("customIcon", .integer).notNull().defaults(to: 0)
                t.column("filterAllPodcasts", .boolean).notNull().defaults(to: false)
                t.column("filterAudioVideoType", .integer).notNull().defaults(to: 0)
                t.column("filterDownloaded", .boolean).notNull().defaults(to: false)
                t.column("filterDownloading", .boolean).notNull().defaults(to: false)
                t.column("filterFinished", .boolean).notNull().defaults(to: false)
                t.column("filterNotDownloaded", .boolean).notNull().defaults(to: false)
                t.column("filterPartiallyPlayed", .boolean).notNull().defaults(to: false)
                t.column("filterStarred", .boolean).notNull().defaults(to: false)
                t.column("filterUnplayed", .boolean).notNull().defaults(to: false)
                t.column("manual", .boolean).notNull().defaults(to: false)
                t.column("playlistName", .text).notNull().defaults(to: "")
                t.column("podcastUuids", .text)
                t.column("sortPosition", .integer).notNull().defaults(to: 0)
                t.column("sortType", .integer).notNull().defaults(to: 0)
                t.column("uuid", .text).notNull().defaults(to: "")
                t.column("syncStatus", .integer).notNull().defaults(to: 0)
                t.column("wasDeleted", .boolean).notNull().defaults(to: false)
                t.column("filterHours", .integer).notNull().defaults(to: 0)
                t.column("autoDownloadLimit", .integer).notNull().defaults(to: 0)
                t.column("filterDuration", .boolean).notNull().defaults(to: false)
                t.column("longerThan", .integer).notNull().defaults(to: 0)
                t.column("shorterThan", .integer).notNull().defaults(to: 0)
                t.column("showArchivedEpisodes", .boolean).notNull().defaults(to: false)
                t.column("playlistUpdateDate", .double)
            }

            try db.create(table: PlaylistEpisodeRecord.databaseTableName, ifNotExists: true) { t in
                t.autoIncrementedPrimaryKey("id")
                t.column("episodePosition", .integer).notNull().defaults(to: 0)
                t.column("episodeUuid", .text)
                t.column("playlist_id", .integer)
                t.column("playlist_uuid", .text)
                t.column("title", .text)
                t.column("podcastUuid", .text)
                t.column("wasDeleted", .boolean).notNull().defaults(to: false)
            }
        }
    }

    override func tearDown() async throws {
        playlistDataManager = nil
        try await super.tearDown()
    }

    // MARK: - Count Query Tests

    func testCountQueryIncludeDeleted() throws {
        // Call the SQL implementation to capture the query
        _ = playlistDataManager.count(includeDeleted: true, dbQueue: sqlCapturingQueue)
        let capturedSQL = sqlCapturingQueue.lastCapturedSQL!

        // Build the equivalent GRDB query
        let grdbRequest = PlaylistRecord.all()
        let grdbSQL = try extractCountSQL(grdbRequest)

        // Compare the SQL
        assertSQLEquivalent(capturedSQL, grdbSQL)
    }

    func testCountQueryExcludeDeleted() throws {
        // Call the SQL implementation to capture the query
        _ = playlistDataManager.count(includeDeleted: false, dbQueue: sqlCapturingQueue)
        let capturedSQL = sqlCapturingQueue.lastCapturedSQL!

        // Build the equivalent GRDB query
        let grdbRequest = PlaylistRecord
            .filter(PlaylistRecord.Columns.wasDeleted == false)
        let grdbSQL = try extractCountSQL(grdbRequest)

        // Compare the SQL
        assertSQLEquivalent(capturedSQL, grdbSQL)
    }

    // MARK: - Find By UUID Tests

    func testFindByUuidQuery() throws {
        // Call the SQL implementation to capture the query
        _ = playlistDataManager.findBy(uuid: "test-uuid", dbQueue: sqlCapturingQueue)
        let capturedSQL = sqlCapturingQueue.lastCapturedSQL!

        // Build the equivalent GRDB query
        let grdbRequest = PlaylistRecord
            .filter(PlaylistRecord.Columns.uuid == "test-uuid")
        let grdbSQL = try extractSQL(grdbRequest)

        // Compare the SQL
        assertSQLEquivalent(capturedSQL, grdbSQL)
    }

    // MARK: - All Playlists Query Tests

    func testAllPlaylistsQueryIncludeDeleted() throws {
        // Call the SQL implementation to capture the query
        _ = playlistDataManager.allPlaylists(includeDeleted: true, dbQueue: sqlCapturingQueue)
        let capturedSQL = sqlCapturingQueue.lastCapturedSQL!

        // Build the equivalent GRDB query
        let grdbRequest = PlaylistRecord
            .order(PlaylistRecord.Columns.sortPosition.asc)
        let grdbSQL = try extractSQL(grdbRequest)

        // Compare the SQL
        assertSQLEquivalent(capturedSQL, grdbSQL)
    }

    func testAllPlaylistsQueryExcludeDeleted() throws {
        // Call the SQL implementation to capture the query
        _ = playlistDataManager.allPlaylists(includeDeleted: false, dbQueue: sqlCapturingQueue)
        let capturedSQL = sqlCapturingQueue.lastCapturedSQL!

        // Build the equivalent GRDB query
        let grdbRequest = PlaylistRecord
            .filter(PlaylistRecord.Columns.wasDeleted == false)
            .order(PlaylistRecord.Columns.sortPosition.asc)
        let grdbSQL = try extractSQL(grdbRequest)

        // Compare the SQL
        assertSQLEquivalent(capturedSQL, grdbSQL)
    }

    // MARK: - All Smart Playlists Query Tests

    func testAllSmartPlaylistsQueryIncludeDeleted() throws {
        // Call the SQL implementation to capture the query
        _ = playlistDataManager.allSmartPlaylists(includeDeleted: true, dbQueue: sqlCapturingQueue)
        let capturedSQL = sqlCapturingQueue.lastCapturedSQL!

        // Build the equivalent GRDB query
        let grdbRequest = PlaylistRecord
            .filter(PlaylistRecord.Columns.manual == false)
            .order(PlaylistRecord.Columns.sortPosition.asc)
        let grdbSQL = try extractSQL(grdbRequest)

        // Compare the SQL
        assertSQLEquivalent(capturedSQL, grdbSQL)
    }

    func testAllSmartPlaylistsQueryExcludeDeleted() throws {
        // Call the SQL implementation to capture the query
        _ = playlistDataManager.allSmartPlaylists(includeDeleted: false, dbQueue: sqlCapturingQueue)
        let capturedSQL = sqlCapturingQueue.lastCapturedSQL!

        // Build the equivalent GRDB query
        let grdbRequest = PlaylistRecord
            .filter(PlaylistRecord.Columns.manual == false)
            .filter(PlaylistRecord.Columns.wasDeleted == false)
            .order(PlaylistRecord.Columns.sortPosition.asc)
        let grdbSQL = try extractSQL(grdbRequest)

        // Compare the SQL
        assertSQLEquivalent(capturedSQL, grdbSQL)
    }

    // MARK: - All Manual Playlists Query Tests

    func testAllManualPlaylistsQueryIncludeDeleted() throws {
        // Call the SQL implementation to capture the query
        _ = playlistDataManager.allManualPlaylists(includeDeleted: true, dbQueue: sqlCapturingQueue)
        let capturedSQL = sqlCapturingQueue.lastCapturedSQL!

        // Build the equivalent GRDB query
        let grdbRequest = PlaylistRecord
            .filter(PlaylistRecord.Columns.manual == true)
            .order(PlaylistRecord.Columns.sortPosition.asc)
        let grdbSQL = try extractSQL(grdbRequest)

        // Compare the SQL
        assertSQLEquivalent(capturedSQL, grdbSQL)
    }

    func testAllManualPlaylistsQueryExcludeDeleted() throws {
        // Call the SQL implementation to capture the query
        _ = playlistDataManager.allManualPlaylists(includeDeleted: false, dbQueue: sqlCapturingQueue)
        let capturedSQL = sqlCapturingQueue.lastCapturedSQL!

        // Build the equivalent GRDB query
        let grdbRequest = PlaylistRecord
            .filter(PlaylistRecord.Columns.manual == true)
            .filter(PlaylistRecord.Columns.wasDeleted == false)
            .order(PlaylistRecord.Columns.sortPosition.asc)
        let grdbSQL = try extractSQL(grdbRequest)

        // Compare the SQL
        assertSQLEquivalent(capturedSQL, grdbSQL)
    }

    // MARK: - All Unsynced Playlists Query Tests

    func testAllUnsyncedPlaylistsQuery() throws {
        // Call the SQL implementation to capture the query
        _ = playlistDataManager.allUnsyncedPlaylists(dbQueue: sqlCapturingQueue)
        let capturedSQL = sqlCapturingQueue.lastCapturedSQL!

        // Build the equivalent GRDB query
        let grdbRequest = PlaylistRecord
            .filter(PlaylistRecord.Columns.syncStatus == SyncStatus.notSynced.rawValue)
            .order(PlaylistRecord.Columns.sortPosition.asc)
        let grdbSQL = try extractSQL(grdbRequest)

        // Compare the SQL
        assertSQLEquivalent(capturedSQL, grdbSQL)
    }

    // MARK: - Playlist Contains Episode Query Tests

    func testPlaylistContainsEpisodeQueryIncludeDeleted() throws {
        // Call the SQL implementation to capture the query
        _ = playlistDataManager.playlistContainsEpisode(episodeUuid: "test-episode-uuid", includeDeleted: true, dbQueue: sqlCapturingQueue)
        let capturedSQL = sqlCapturingQueue.lastCapturedSQL!

        // Build the equivalent GRDB query
        let grdbRequest = PlaylistEpisodeRecord
            .filter(PlaylistEpisodeRecord.Columns.episodeUuid == "test-episode-uuid")
            .filter(PlaylistEpisodeRecord.Columns.playlist_uuid != nil)
            .limit(1)
        let grdbSQL = try extractSQL(grdbRequest)

        // Compare the SQL
        assertSQLEquivalent(capturedSQL, grdbSQL)
    }

    func testPlaylistContainsEpisodeQueryExcludeDeleted() throws {
        // Call the SQL implementation to capture the query
        _ = playlistDataManager.playlistContainsEpisode(episodeUuid: "test-episode-uuid", includeDeleted: false, dbQueue: sqlCapturingQueue)
        let capturedSQL = sqlCapturingQueue.lastCapturedSQL!

        // Build the equivalent GRDB query
        let grdbRequest = PlaylistEpisodeRecord
            .filter(PlaylistEpisodeRecord.Columns.episodeUuid == "test-episode-uuid")
            .filter(PlaylistEpisodeRecord.Columns.wasDeleted == false)
            .filter(PlaylistEpisodeRecord.Columns.playlist_uuid != nil)
            .limit(1)
        let grdbSQL = try extractSQL(grdbRequest)

        // Compare the SQL
        assertSQLEquivalent(capturedSQL, grdbSQL)
    }

    // MARK: - Manual Playlist UUIDs Query Tests

    func testManualPlaylistUUIDsQuery() throws {
        // Call the SQL implementation to capture the query
        // SQL implementation uses: SELECT playlist_uuid FROM SJPlaylistEpisode WHERE episodeUuid = ? GROUP BY playlist_uuid
        _ = playlistDataManager.manualPlaylistUUIDs(for: "test-episode-uuid", dbQueue: sqlCapturingQueue)
        let capturedSQL = sqlCapturingQueue.lastCapturedSQL!

        // Build the equivalent GRDB query with DISTINCT to match GROUP BY behavior
        let grdbRequest = PlaylistEpisodeRecord
            .filter(PlaylistEpisodeRecord.Columns.episodeUuid == "test-episode-uuid")
            .select(PlaylistEpisodeRecord.Columns.playlist_uuid)
            .distinct()
        let grdbSQL = try extractSQL(grdbRequest)

        // Compare the SQL
        assertSQLEquivalent(capturedSQL, grdbSQL)
    }

    // MARK: - Next/First Sort Position Query Tests

    func testNextSortPositionQuery() throws {
        // Call the SQL implementation to capture the query
        _ = playlistDataManager.nextSortPositionForPlaylist(dbQueue: sqlCapturingQueue)
        let capturedSQL = sqlCapturingQueue.lastCapturedSQL!

        // Build the equivalent GRDB query
        let grdbRequest = PlaylistRecord.select(max(PlaylistRecord.Columns.sortPosition))
        let grdbSQL = try extractAggregateSQL(grdbRequest)

        // Compare the SQL
        assertSQLEquivalent(capturedSQL, grdbSQL)
    }

    func testFirstSortPositionQuery() throws {
        // Call the SQL implementation to capture the query
        _ = playlistDataManager.firstSortPositionForPlaylist(dbQueue: sqlCapturingQueue)
        let capturedSQL = sqlCapturingQueue.lastCapturedSQL!

        // Build the equivalent GRDB query
        let grdbRequest = PlaylistRecord.select(min(PlaylistRecord.Columns.sortPosition))
        let grdbSQL = try extractAggregateSQL(grdbRequest)

        // Compare the SQL
        assertSQLEquivalent(capturedSQL, grdbSQL)
    }

    // MARK: - Delete Query Tests

    func testDeleteDeletedPlaylistsQuery() throws {
        // Call the SQL implementation to capture the query
        playlistDataManager.deleteDeletedPlaylists(dbQueue: sqlCapturingQueue)
        let capturedSQL = sqlCapturingQueue.lastCapturedSQL!

        // Build the equivalent GRDB query
        let grdbRequest = PlaylistRecord
            .filter(PlaylistRecord.Columns.wasDeleted == true)
        let grdbSQL = try extractDeleteSQL(grdbRequest)

        // Compare the SQL
        assertSQLEquivalent(capturedSQL, grdbSQL)
    }
}
