import XCTest
import GRDB
@testable import PocketCastsDataModel
@testable import PocketCastsUtils

/// Tests that validate the SQL queries generated by GRDB QueryInterface
/// match the raw SQL queries in the SQL implementation for PodcastDataManager.
final class PodcastDataManagerQueryTests: SQLQueryComparisonTestCase {

    // MARK: - Test Setup

    override func setUp() async throws {
        try await super.setUp()

        // Create the schema in GRDB for SQL extraction
        try await grdbQueue.write { db in
            try db.create(table: PodcastRecord.databaseTableName, ifNotExists: true) { t in
                t.autoIncrementedPrimaryKey("id")
                t.column("addedDate", .double)
                t.column("autoDownloadSetting", .integer).notNull().defaults(to: 0)
                t.column("autoAddToUpNext", .integer).notNull().defaults(to: 0)
                t.column("episodeKeepSetting", .integer).notNull().defaults(to: 0)
                t.column("backgroundColor", .text)
                t.column("detailColor", .text)
                t.column("primaryColor", .text)
                t.column("secondaryColor", .text)
                t.column("lastColorDownloadDate", .double)
                t.column("imageURL", .text)
                t.column("latestEpisodeUuid", .text)
                t.column("latestEpisodeDate", .double)
                t.column("mediaType", .text)
                t.column("lastThumbnailDownloadDate", .double)
                t.column("thumbnailStatus", .integer).notNull().defaults(to: 1)
                t.column("podcastUrl", .text)
                t.column("author", .text)
                t.column("playbackSpeed", .double).notNull().defaults(to: 1)
                t.column("boostVolume", .boolean).notNull().defaults(to: false)
                t.column("trimSilenceAmount", .integer).notNull().defaults(to: 0)
                t.column("podcastCategory", .text)
                t.column("podcastDescription", .text)
                t.column("podcastHTMLDescription", .text)
                t.column("sortOrder", .integer).notNull().defaults(to: 0)
                t.column("startFrom", .integer).notNull().defaults(to: 0)
                t.column("skipLast", .integer).notNull().defaults(to: 0)
                t.column("subscribed", .integer).notNull().defaults(to: 1)
                t.column("title", .text)
                t.column("uuid", .text).notNull().defaults(to: "")
                t.column("syncStatus", .integer).notNull().defaults(to: 0)
                t.column("colorVersion", .integer).notNull().defaults(to: 1)
                t.column("pushEnabled", .boolean).notNull().defaults(to: false)
                t.column("episodeSortOrder", .integer).notNull().defaults(to: 1)
                t.column("showType", .text)
                t.column("estimatedNextEpisode", .double)
                t.column("episodeFrequency", .text)
                t.column("lastUpdatedAt", .text)
                t.column("excludeFromAutoArchive", .boolean).notNull().defaults(to: false)
                t.column("overrideGlobalEffects", .boolean).notNull().defaults(to: false)
                t.column("overrideGlobalArchive", .boolean).notNull().defaults(to: false)
                t.column("autoArchivePlayedAfter", .double).notNull().defaults(to: 0)
                t.column("autoArchiveInactiveAfter", .double).notNull().defaults(to: 0)
                t.column("episodeGrouping", .integer).notNull().defaults(to: 0)
                t.column("isPaid", .boolean).notNull().defaults(to: false)
                t.column("licensing", .integer).notNull().defaults(to: 0)
                t.column("fullSyncLastSyncAt", .text)
                t.column("showArchived", .boolean).notNull().defaults(to: false)
                t.column("refreshAvailable", .boolean).notNull().defaults(to: false)
                t.column("folderUuid", .text)
                t.column("usedCustomEffectsBefore", .boolean).notNull().defaults(to: false)
                t.column("isPrivate", .boolean).notNull().defaults(to: false)
                t.column("fundingURL", .text)
                t.column("settings", .text).notNull().defaults(to: "")
            }
        }
    }

    // MARK: - Find By UUID Query Tests

    func testFindByUuidQuery() throws {
        let grdbRequest = PodcastRecord
            .filter(PodcastRecord.Columns.uuid == "test-uuid")
        let grdbSQL = try extractSQL(grdbRequest)

        // SQL implementation: "SELECT * from SJPodcast WHERE uuid = ?"
        let expectedSQL = "SELECT * FROM \"SJPodcast\" WHERE \"uuid\" = 'test-uuid'"
        assertSQLEquivalent(grdbSQL, expectedSQL)
    }

    // MARK: - All Podcasts Query Tests

    func testAllPodcastsQuery() throws {
        let grdbRequest = PodcastRecord
            .order(PodcastRecord.Columns.sortOrder.asc)
        let grdbSQL = try extractSQL(grdbRequest)

        // SQL implementation: "SELECT * from SJPodcast ORDER BY sortOrder ASC"
        let expectedSQL = "SELECT * FROM \"SJPodcast\" ORDER BY \"sortOrder\" ASC"
        assertSQLEquivalent(grdbSQL, expectedSQL)
    }

    // MARK: - All Subscribed Podcasts Query Tests

    func testAllSubscribedPodcastsQuery() throws {
        let grdbRequest = PodcastRecord
            .filter(PodcastRecord.Columns.subscribed == 1)
            .order(PodcastRecord.Columns.sortOrder.asc)
        let grdbSQL = try extractSQL(grdbRequest)

        // SQL implementation: "SELECT * from SJPodcast WHERE subscribed = 1 ORDER BY sortOrder ASC"
        let expectedSQL = "SELECT * FROM \"SJPodcast\" WHERE \"subscribed\" = 1 ORDER BY \"sortOrder\" ASC"
        assertSQLEquivalent(grdbSQL, expectedSQL)
    }

    // MARK: - Random Podcasts Query Tests

    func testRandomPodcastsQuery() throws {
        let grdbRequest = PodcastRecord
            .order(sql: "RANDOM()")
            .limit(5)
        let grdbSQL = try extractSQL(grdbRequest)

        // SQL implementation: "SELECT * FROM SJPodcast ORDER BY RANDOM() LIMIT 5"
        let expectedSQL = "SELECT * FROM \"SJPodcast\" ORDER BY RANDOM() LIMIT 5"
        assertSQLEquivalent(grdbSQL, expectedSQL)
    }

    // MARK: - Count Podcasts In Folder Query Tests

    func testCountPodcastsInFolderWithFolderUuidQuery() throws {
        let grdbRequest = PodcastRecord
            .filter(PodcastRecord.Columns.subscribed == 1)
            .filter(PodcastRecord.Columns.folderUuid == "folder-uuid")
        let grdbSQL = try extractCountSQL(grdbRequest)

        // SQL implementation: "SELECT COUNT(*) FROM SJPodcast WHERE subscribed = 1 AND folderUuid = ?"
        let expectedSQL = "SELECT COUNT(*) FROM \"SJPodcast\" WHERE (\"subscribed\" = 1) AND (\"folderUuid\" = 'folder-uuid')"
        assertSQLEquivalent(grdbSQL, expectedSQL)
    }

    func testCountPodcastsWithNoFolderQuery() throws {
        let grdbRequest = PodcastRecord
            .filter(PodcastRecord.Columns.subscribed == 1)
            .filter(PodcastRecord.Columns.folderUuid == nil)
        let grdbSQL = try extractCountSQL(grdbRequest)

        // SQL implementation: "SELECT COUNT(*) FROM SJPodcast WHERE subscribed = 1 AND folderUuid IS NULL"
        let expectedSQL = "SELECT COUNT(*) FROM \"SJPodcast\" WHERE (\"subscribed\" = 1) AND (\"folderUuid\" IS NULL)"
        assertSQLEquivalent(grdbSQL, expectedSQL)
    }

    // MARK: - All Unsynced Podcasts Query Tests

    func testAllUnsyncedPodcastsQuery() throws {
        let grdbRequest = PodcastRecord
            .filter(PodcastRecord.Columns.syncStatus == SyncStatus.notSynced.rawValue)
        let grdbSQL = try extractSQL(grdbRequest)

        // SQL implementation: "SELECT * from SJPodcast WHERE syncStatus = ?"
        let expectedSQL = "SELECT * FROM \"SJPodcast\" WHERE \"syncStatus\" = \(SyncStatus.notSynced.rawValue)"
        assertSQLEquivalent(grdbSQL, expectedSQL)
    }

    // MARK: - Delete Podcast Query Tests

    func testDeleteByUuidQuery() throws {
        let grdbRequest = PodcastRecord
            .filter(PodcastRecord.Columns.uuid == "test-uuid")
        let grdbSQL = try extractDeleteSQL(grdbRequest)

        // SQL implementation: "DELETE FROM SJPodcast WHERE uuid = ?"
        let expectedSQL = "DELETE FROM \"SJPodcast\" WHERE \"uuid\" = 'test-uuid'"
        assertSQLEquivalent(grdbSQL, expectedSQL)
    }

    // MARK: - Update Query Tests

    func testMarkAllSyncedQuery() throws {
        // This updates all podcasts, no filter needed for the SQL part
        let grdbRequest = PodcastRecord.all()
        let grdbSQL = try extractUpdateSQL(grdbRequest, assignments: [
            PodcastRecord.Columns.syncStatus.set(to: SyncStatus.synced.rawValue)
        ])

        // SQL implementation: "UPDATE SJPodcast SET syncStatus = ?"
        let expectedSQL = "UPDATE \"SJPodcast\" SET \"syncStatus\" = \(SyncStatus.synced.rawValue)"
        assertSQLEquivalent(grdbSQL, expectedSQL)
    }

    func testMarkAllUnsyncedQuery() throws {
        let grdbRequest = PodcastRecord
            .filter(PodcastRecord.Columns.subscribed == 1)
        let grdbSQL = try extractUpdateSQL(grdbRequest, assignments: [
            PodcastRecord.Columns.syncStatus.set(to: SyncStatus.notSynced.rawValue)
        ])

        // SQL implementation: "UPDATE SJPodcast SET syncStatus = ? WHERE subscribed = 1"
        let expectedSQL = "UPDATE \"SJPodcast\" SET \"syncStatus\" = \(SyncStatus.notSynced.rawValue) WHERE \"subscribed\" = 1"
        assertSQLEquivalent(grdbSQL, expectedSQL)
    }

    func testRemoveAllPodcastsFromAllFoldersQuery() throws {
        // This updates all podcasts, no filter needed
        let grdbRequest = PodcastRecord.all()
        let grdbSQL = try extractUpdateSQL(grdbRequest, assignments: [
            PodcastRecord.Columns.folderUuid.set(to: nil)
        ])

        // SQL implementation: "UPDATE SJPodcast SET folderUuid = NULL"
        let expectedSQL = "UPDATE \"SJPodcast\" SET \"folderUuid\" = NULL"
        assertSQLEquivalent(grdbSQL, expectedSQL)
    }

    func testRemoveAllPodcastsFromFolderQuery() throws {
        let grdbRequest = PodcastRecord
            .filter(PodcastRecord.Columns.folderUuid == "folder-uuid")
        let grdbSQL = try extractUpdateSQL(grdbRequest, assignments: [
            PodcastRecord.Columns.folderUuid.set(to: nil),
            PodcastRecord.Columns.syncStatus.set(to: SyncStatus.notSynced.rawValue)
        ])

        // SQL implementation: "UPDATE SJPodcast SET folderUuid = NULL, syncStatus = ? WHERE folderUuid = ?"
        let expectedSQL = "UPDATE \"SJPodcast\" SET \"folderUuid\" = NULL, \"syncStatus\" = \(SyncStatus.notSynced.rawValue) WHERE \"folderUuid\" = 'folder-uuid'"
        assertSQLEquivalent(grdbSQL, expectedSQL)
    }

    func testUpdateAllPodcastGroupingQuery() throws {
        let grouping = PodcastGrouping.none
        let grdbRequest = PodcastRecord
            .filter(PodcastRecord.Columns.subscribed == 1)
        let grdbSQL = try extractUpdateSQL(grdbRequest, assignments: [
            PodcastRecord.Columns.episodeGrouping.set(to: grouping.rawValue)
        ])

        // SQL implementation: "UPDATE SJPodcast SET episodeGrouping = ? WHERE subscribed = 1"
        let expectedSQL = "UPDATE \"SJPodcast\" SET \"episodeGrouping\" = \(grouping.rawValue) WHERE \"subscribed\" = 1"
        assertSQLEquivalent(grdbSQL, expectedSQL)
    }

    func testUpdateAllShowArchivedQuery() throws {
        let grdbRequest = PodcastRecord
            .filter(PodcastRecord.Columns.subscribed == 1)
        let grdbSQL = try extractUpdateSQL(grdbRequest, assignments: [
            PodcastRecord.Columns.showArchived.set(to: true)
        ])

        // SQL implementation: "UPDATE SJPodcast SET showArchived = ? WHERE subscribed = 1"
        let expectedSQL = "UPDATE \"SJPodcast\" SET \"showArchived\" = 1 WHERE \"subscribed\" = 1"
        assertSQLEquivalent(grdbSQL, expectedSQL)
    }
}
