import XCTest
import GRDB
@testable import PocketCastsDataModel
@testable import PocketCastsUtils

/// Tests that validate the SQL queries generated by GRDB QueryInterface
/// match the raw SQL queries in the SQL implementation for UpNextDataManager.
///
/// These tests work by:
/// 1. Calling the SQL implementation method with a capturing database queue
/// 2. Extracting the SQL from the equivalent GRDB QueryInterface request
/// 3. Comparing the two SQL strings to ensure they match
final class UpNextDataManagerQueryTests: SQLQueryComparisonTestCase {

    // MARK: - Test Setup

    private var upNextDataManager: UpNextDataManager!
    private let upNextPlaylistId = Int64(UpNextDataManager.upNextPlaylistId)

    override func setUp() async throws {
        try await super.setUp()
        upNextDataManager = UpNextDataManager()

        // Create the schema in GRDB for SQL extraction
        try await grdbQueue.write { db in
            try db.create(table: PlaylistEpisodeRecord.databaseTableName, ifNotExists: true) { t in
                t.autoIncrementedPrimaryKey("id")
                t.column("episodePosition", .integer).notNull().defaults(to: 0)
                t.column("episodeUuid", .text).notNull().defaults(to: "")
                t.column("playlist_id", .integer).notNull().defaults(to: 0)
                t.column("playlist_uuid", .text)
                t.column("timeModified", .integer).notNull().defaults(to: 0)
                t.column("wasDeleted", .boolean).notNull().defaults(to: false)
                t.column("title", .text)
                t.column("podcastUuid", .text)
            }
        }
    }

    override func tearDown() async throws {
        upNextDataManager = nil
        try await super.tearDown()
    }

    // MARK: - Delete Playlist Episode Query Tests

    func testDeletePlaylistEpisodeQuery() throws {
        // Create a mock playlist episode
        let playlistEpisode = PlaylistEpisode()
        playlistEpisode.id = 123
        playlistEpisode.episodeUuid = "test-uuid"

        // Call the SQL implementation to capture the query
        upNextDataManager.delete(playlistEpisode: playlistEpisode, dbQueue: sqlCapturingQueue)

        // Find the DELETE query and expand placeholders
        let deleteQuery = sqlCapturingQueue.capturedQueries.first { $0.sql.uppercased().starts(with: "DELETE") }
        let capturedSQL = sqlCapturingQueue.expandSQL(deleteQuery!.sql, values: deleteQuery?.values)

        // Build the equivalent GRDB query
        let grdbRequest = PlaylistEpisodeRecord
            .filter(PlaylistEpisodeRecord.Columns.id == Int64(123))
            .filter(PlaylistEpisodeRecord.Columns.playlist_id == upNextPlaylistId)
        let grdbSQL = try extractDeleteSQL(grdbRequest)

        // Compare the SQL
        assertSQLEquivalent(capturedSQL, grdbSQL)
    }

    // MARK: - Delete All Up Next Episodes Query Tests

    func testDeleteAllUpNextEpisodesQuery() throws {
        // Call the SQL implementation to capture the query
        upNextDataManager.deleteAllUpNextEpisodes(dbQueue: sqlCapturingQueue)

        // Find the DELETE query and expand placeholders
        let deleteQuery = sqlCapturingQueue.capturedQueries.first { $0.sql.uppercased().starts(with: "DELETE") }
        let capturedSQL = sqlCapturingQueue.expandSQL(deleteQuery!.sql, values: deleteQuery?.values)

        // Build the equivalent GRDB query
        let grdbRequest = PlaylistEpisodeRecord
            .filter(PlaylistEpisodeRecord.Columns.playlist_id == upNextPlaylistId)
        let grdbSQL = try extractDeleteSQL(grdbRequest)

        // Compare the SQL
        assertSQLEquivalent(capturedSQL, grdbSQL)
    }

    // MARK: - Delete All Up Next Episodes Except Query Tests

    func testDeleteAllUpNextEpisodesExceptQuery() throws {
        // Call the SQL implementation to capture the query
        upNextDataManager.deleteAllUpNextEpisodesExcept(episodeUuid: "keep-episode-uuid", dbQueue: sqlCapturingQueue)

        // Find the DELETE query and expand placeholders
        let deleteQuery = sqlCapturingQueue.capturedQueries.first { $0.sql.uppercased().starts(with: "DELETE") }
        let capturedSQL = sqlCapturingQueue.expandSQL(deleteQuery!.sql, values: deleteQuery?.values)

        // Build the equivalent GRDB query
        let grdbRequest = PlaylistEpisodeRecord
            .filter(PlaylistEpisodeRecord.Columns.episodeUuid != "keep-episode-uuid")
            .filter(PlaylistEpisodeRecord.Columns.playlist_id == upNextPlaylistId)
        let grdbSQL = try extractDeleteSQL(grdbRequest)

        // Compare the SQL
        assertSQLEquivalent(capturedSQL, grdbSQL)
    }

    // MARK: - Delete All Up Next Episodes Not In Query Tests

    func testDeleteAllUpNextEpisodesNotInWithEmptyListQuery() throws {
        // When uuids is empty, delete all episodes for the playlist
        upNextDataManager.deleteAllUpNextEpisodesNotIn(uuids: [], dbQueue: sqlCapturingQueue)

        // Find the DELETE query and expand placeholders
        let deleteQuery = sqlCapturingQueue.capturedQueries.first { $0.sql.uppercased().starts(with: "DELETE") }
        let capturedSQL = sqlCapturingQueue.expandSQL(deleteQuery!.sql, values: deleteQuery?.values)

        // Build the equivalent GRDB query
        let grdbRequest = PlaylistEpisodeRecord
            .filter(PlaylistEpisodeRecord.Columns.playlist_id == upNextPlaylistId)
        let grdbSQL = try extractDeleteSQL(grdbRequest)

        // Compare the SQL
        assertSQLEquivalent(capturedSQL, grdbSQL)
    }

    func testDeleteAllUpNextEpisodesNotInWithUuidsQuery() throws {
        let uuids = ["uuid-1", "uuid-2", "uuid-3"]

        // Call the SQL implementation to capture the query
        upNextDataManager.deleteAllUpNextEpisodesNotIn(uuids: uuids, dbQueue: sqlCapturingQueue)

        // Find the DELETE query and expand placeholders
        let deleteQuery = sqlCapturingQueue.capturedQueries.first { $0.sql.uppercased().starts(with: "DELETE") }
        let capturedSQL = sqlCapturingQueue.expandSQL(deleteQuery!.sql, values: deleteQuery?.values)

        // Build the equivalent GRDB query
        let grdbRequest = PlaylistEpisodeRecord
            .filter(!uuids.contains(PlaylistEpisodeRecord.Columns.episodeUuid))
            .filter(PlaylistEpisodeRecord.Columns.playlist_id == upNextPlaylistId)
        let grdbSQL = try extractDeleteSQL(grdbRequest)

        // Compare the SQL
        assertSQLEquivalent(capturedSQL, grdbSQL)
    }

    // MARK: - Delete All Up Next Episodes In Query Tests

    func testDeleteAllUpNextEpisodesInQuery() throws {
        let uuids = ["uuid-1", "uuid-2"]

        // Call the SQL implementation to capture the query
        upNextDataManager.deleteAllUpNextEpisodesIn(uuids: uuids, dbQueue: sqlCapturingQueue)

        // Find the DELETE query and expand placeholders
        let deleteQuery = sqlCapturingQueue.capturedQueries.first { $0.sql.uppercased().starts(with: "DELETE") }
        let capturedSQL = sqlCapturingQueue.expandSQL(deleteQuery!.sql, values: deleteQuery?.values)

        // Build the equivalent GRDB query
        let grdbRequest = PlaylistEpisodeRecord
            .filter(uuids.contains(PlaylistEpisodeRecord.Columns.episodeUuid))
            .filter(PlaylistEpisodeRecord.Columns.playlist_id == upNextPlaylistId)
        let grdbSQL = try extractDeleteSQL(grdbRequest)

        // Compare the SQL
        assertSQLEquivalent(capturedSQL, grdbSQL)
    }
}
