import XCTest
import GRDB
@testable import PocketCastsDataModel
@testable import PocketCastsUtils

/// Tests that validate the SQL queries generated by GRDB QueryInterface
/// match the raw SQL queries in the SQL implementation for UpNextChangesDataManager.
///
/// These tests work by:
/// 1. Calling the SQL implementation method with a capturing database queue
/// 2. Extracting the SQL from the equivalent GRDB QueryInterface request
/// 3. Comparing the two SQL strings to ensure they match
final class UpNextChangesDataManagerQueryTests: SQLQueryComparisonTestCase {

    // MARK: - Test Setup

    private var upNextChangesDataManager: UpNextChangesDataManager!

    override func setUp() async throws {
        try await super.setUp()
        upNextChangesDataManager = UpNextChangesDataManager()

        // Create the schema in GRDB for SQL extraction
        try await grdbQueue.write { db in
            try db.create(table: UpNextChangesRecord.databaseTableName, ifNotExists: true) { t in
                t.autoIncrementedPrimaryKey("id")
                t.column("type", .integer).notNull().defaults(to: 0)
                t.column("uuid", .text)
                t.column("uuids", .text)
                t.column("utcTime", .integer).notNull().defaults(to: 0)
            }
        }
    }

    override func tearDown() async throws {
        upNextChangesDataManager = nil
        try await super.tearDown()
    }

    // MARK: - Find Replace Action Query Tests

    func testFindReplaceActionQuery() throws {
        // Call the SQL implementation to capture the query
        _ = upNextChangesDataManager.findReplaceAction(dbQueue: sqlCapturingQueue)
        let capturedSQL = sqlCapturingQueue.lastCapturedSQL!

        // Build the equivalent GRDB query
        let grdbRequest = UpNextChangesRecord
            .filter(UpNextChangesRecord.Columns.type == UpNextChanges.Actions.replace.rawValue)
        let grdbSQL = try extractSQL(grdbRequest)

        // Compare the SQL
        assertSQLEquivalent(capturedSQL, grdbSQL)
    }

    // MARK: - Find Update Actions Query Tests

    func testFindUpdateActionsQuery() throws {
        // Call the SQL implementation to capture the query
        _ = upNextChangesDataManager.findUpdateActions(dbQueue: sqlCapturingQueue)
        let capturedSQL = sqlCapturingQueue.lastCapturedSQL!

        // Build the equivalent GRDB query
        let grdbRequest = UpNextChangesRecord
            .filter(UpNextChangesRecord.Columns.type != UpNextChanges.Actions.replace.rawValue)
        let grdbSQL = try extractSQL(grdbRequest)

        // Compare the SQL
        assertSQLEquivalent(capturedSQL, grdbSQL)
    }

    // MARK: - Delete Changes Older Than Query Tests

    func testDeleteChangesOlderThanQuery() throws {
        let utcTime = Int64(1000000)

        // Call the SQL implementation to capture the query
        upNextChangesDataManager.deleteChangesOlderThan(utcTime: utcTime, dbQueue: sqlCapturingQueue)
        let capturedSQL = sqlCapturingQueue.lastCapturedSQL!

        // Build the equivalent GRDB query
        let grdbRequest = UpNextChangesRecord
            .filter(UpNextChangesRecord.Columns.utcTime <= utcTime)
        let grdbSQL = try extractDeleteSQL(grdbRequest)

        // Compare the SQL
        assertSQLEquivalent(capturedSQL, grdbSQL)
    }

    // MARK: - Delete Changes For Episode Query Tests

    func testDeleteChangesForEpisodeQuery() throws {
        // Call the SQL implementation to capture the query
        // Note: saveUpNextRemove first deletes existing changes for the episode
        upNextChangesDataManager.saveUpNextRemove(episodeUuid: "episode-uuid", dbQueue: sqlCapturingQueue)

        // The first query should be the DELETE, second is the INSERT
        // Expand placeholders for comparison
        let deleteQuery = sqlCapturingQueue.capturedQueries.first!
        let capturedSQL = sqlCapturingQueue.expandSQL(deleteQuery.sql, values: deleteQuery.values)

        // Build the equivalent GRDB query
        let grdbRequest = UpNextChangesRecord
            .filter(UpNextChangesRecord.Columns.uuid == "episode-uuid")
        let grdbSQL = try extractDeleteSQL(grdbRequest)

        // Compare the SQL
        assertSQLEquivalent(capturedSQL, grdbSQL)
    }
}
