import XCTest
import GRDB
@testable import PocketCastsDataModel
@testable import PocketCastsUtils

/// Tests that validate the SQL queries generated by GRDB QueryInterface
/// match the raw SQL queries in the SQL implementation for UserEpisodeDataManager.
///
/// These tests work by:
/// 1. Calling the SQL implementation method with a capturing database queue
/// 2. Extracting the SQL from the equivalent GRDB QueryInterface request
/// 3. Comparing the two SQL strings to ensure they match
final class UserEpisodeDataManagerQueryTests: SQLQueryComparisonTestCase {

    // MARK: - Test Setup

    private var userEpisodeDataManager: UserEpisodeDataManager!

    override func setUp() async throws {
        try await super.setUp()
        userEpisodeDataManager = UserEpisodeDataManager()

        // Create the schema in GRDB for SQL extraction
        try await grdbQueue.write { db in
            try db.create(table: UserEpisodeRecord.databaseTableName, ifNotExists: true) { t in
                t.autoIncrementedPrimaryKey("id")
                t.column("addedDate", .double)
                t.column("lastDownloadAttemptDate", .double)
                t.column("downloadErrorDetails", .text)
                t.column("downloadTaskId", .text)
                t.column("downloadUrl", .text)
                t.column("episodeStatus", .integer).notNull().defaults(to: 0)
                t.column("fileType", .text)
                t.column("contentType", .text)
                t.column("playedUpTo", .double).notNull().defaults(to: 0)
                t.column("duration", .double).notNull().defaults(to: 0)
                t.column("playingStatus", .integer).notNull().defaults(to: 0)
                t.column("autoDownloadStatus", .integer).notNull().defaults(to: 0)
                t.column("publishedDate", .double)
                t.column("sizeInBytes", .integer).notNull().defaults(to: 0)
                t.column("playingStatusModified", .integer).notNull().defaults(to: 0)
                t.column("playedUpToModified", .integer).notNull().defaults(to: 0)
                t.column("title", .text)
                t.column("uuid", .text).notNull().defaults(to: "")
                t.column("playbackErrorDetails", .text)
                t.column("cachedFrameCount", .integer).notNull().defaults(to: 0)
                t.column("imageUrl", .text)
                t.column("uploadStatus", .integer).notNull().defaults(to: 0)
                t.column("uploadTaskId", .text)
                t.column("imageColor", .integer).notNull().defaults(to: 0)
                t.column("titleModified", .integer).notNull().defaults(to: 0)
                t.column("imageColorModified", .integer).notNull().defaults(to: 0)
                t.column("imageModified", .integer).notNull().defaults(to: 0)
                t.column("durationModified", .integer).notNull().defaults(to: 0)
                t.column("hasCustomImage", .boolean).notNull().defaults(to: false)
            }
        }
    }

    override func tearDown() async throws {
        userEpisodeDataManager = nil
        try await super.tearDown()
    }

    // MARK: - Find By UUID Query Tests

    func testFindByUuidQuery() throws {
        // Call the SQL implementation to capture the query
        _ = userEpisodeDataManager.findBy(uuid: "test-uuid", dbQueue: sqlCapturingQueue)
        let capturedSQL = sqlCapturingQueue.lastCapturedSQL!
        let capturedValues = sqlCapturingQueue.capturedQueries.last?.values

        // Build the equivalent GRDB query
        let grdbRequest = UserEpisodeRecord
            .filter(UserEpisodeRecord.Columns.uuid == "test-uuid")
        let grdbSQL = try extractSQL(grdbRequest)

        // GRDB parameterizes uuid
        let grdbValues: [Any] = ["test-uuid"]

        // Compare the SQL
        assertSQLEquivalent(capturedSQL, grdbSQL)
    }

    // MARK: - Find By Download Task ID Query Tests

    func testFindByDownloadTaskIdQuery() throws {
        // Call the SQL implementation to capture the query
        _ = userEpisodeDataManager.findBy(downloadTaskId: "task-123", dbQueue: sqlCapturingQueue)
        let capturedSQL = sqlCapturingQueue.lastCapturedSQL!
        let capturedValues = sqlCapturingQueue.capturedQueries.last?.values

        // Build the equivalent GRDB query
        let grdbRequest = UserEpisodeRecord
            .filter(UserEpisodeRecord.Columns.downloadTaskId == "task-123")
        let grdbSQL = try extractSQL(grdbRequest)

        // GRDB parameterizes downloadTaskId
        let grdbValues: [Any] = ["task-123"]

        // Compare the SQL
        assertSQLEquivalent(capturedSQL, grdbSQL)
    }

    // MARK: - Find By Upload Task ID Query Tests

    func testFindByUploadTaskIdQuery() throws {
        // Call the SQL implementation to capture the query
        _ = userEpisodeDataManager.findBy(uploadTaskId: "upload-task-123", dbQueue: sqlCapturingQueue)
        let capturedSQL = sqlCapturingQueue.lastCapturedSQL!
        let capturedValues = sqlCapturingQueue.capturedQueries.last?.values

        // Build the equivalent GRDB query
        let grdbRequest = UserEpisodeRecord
            .filter(UserEpisodeRecord.Columns.uploadTaskId == "upload-task-123")
        let grdbSQL = try extractSQL(grdbRequest)

        // GRDB parameterizes uploadTaskId
        let grdbValues: [Any] = ["upload-task-123"]

        // Compare the SQL
        assertSQLEquivalent(capturedSQL, grdbSQL)
    }

    // MARK: - Find All Query Tests

    func testFindAllNewestToOldestQuery() throws {
        // Call the SQL implementation to capture the query
        _ = userEpisodeDataManager.findAll(sortedBy: .newestToOldest, dbQueue: sqlCapturingQueue)
        let capturedSQL = sqlCapturingQueue.lastCapturedSQL!
        let capturedValues = sqlCapturingQueue.capturedQueries.last?.values

        // Build the equivalent GRDB query
        let grdbRequest = UserEpisodeRecord
            .filter(UserEpisodeRecord.Columns.uploadStatus != UploadStatus.deleteFromCloudPending.rawValue)
            .filter(UserEpisodeRecord.Columns.uploadStatus != UploadStatus.deleteFromCloudAndLocalPending.rawValue)
            .order(UserEpisodeRecord.Columns.addedDate.desc)
        let grdbSQL = try extractSQL(grdbRequest)

        // GRDB parameterizes uploadStatus values
        let grdbValues: [Any] = [UploadStatus.deleteFromCloudPending.rawValue, UploadStatus.deleteFromCloudAndLocalPending.rawValue]

        // Compare the SQL
        assertSQLEquivalent(capturedSQL, grdbSQL)
    }

    func testFindAllOldestToNewestWithLimitQuery() throws {
        // Call the SQL implementation to capture the query
        _ = userEpisodeDataManager.findAll(sortedBy: .oldestToNewest, limit: 10, dbQueue: sqlCapturingQueue)
        let capturedSQL = sqlCapturingQueue.lastCapturedSQL!
        let capturedValues = sqlCapturingQueue.capturedQueries.last?.values

        // Build the equivalent GRDB query
        let grdbRequest = UserEpisodeRecord
            .filter(UserEpisodeRecord.Columns.uploadStatus != UploadStatus.deleteFromCloudPending.rawValue)
            .filter(UserEpisodeRecord.Columns.uploadStatus != UploadStatus.deleteFromCloudAndLocalPending.rawValue)
            .order(UserEpisodeRecord.Columns.addedDate.asc)
            .limit(10)
        let grdbSQL = try extractSQL(grdbRequest)

        // GRDB parameterizes uploadStatus values
        let grdbValues: [Any] = [UploadStatus.deleteFromCloudPending.rawValue, UploadStatus.deleteFromCloudAndLocalPending.rawValue]

        // Compare the SQL
        assertSQLEquivalent(capturedSQL, grdbSQL)
    }

    // MARK: - Find All Downloaded Query Tests

    func testFindAllDownloadedQuery() throws {
        // Call the SQL implementation to capture the query
        _ = userEpisodeDataManager.findAllDownloaded(sortedBy: .newestToOldest, dbQueue: sqlCapturingQueue)
        let capturedSQL = sqlCapturingQueue.lastCapturedSQL!
        let capturedValues = sqlCapturingQueue.capturedQueries.last?.values

        // Build the equivalent GRDB query
        let grdbRequest = UserEpisodeRecord
            .filter(UserEpisodeRecord.Columns.episodeStatus == DownloadStatus.downloaded.rawValue)
            .order(UserEpisodeRecord.Columns.addedDate.desc)
        let grdbSQL = try extractSQL(grdbRequest)

        // GRDB parameterizes episodeStatus
        let grdbValues: [Any] = [DownloadStatus.downloaded.rawValue]

        // Compare the SQL
        assertSQLEquivalent(capturedSQL, grdbSQL)
    }

    // MARK: - Find All With Upload Status Query Tests

    func testFindAllWithUploadStatusQuery() throws {
        // Call the SQL implementation to capture the query
        _ = userEpisodeDataManager.findAllWithUploadStatus(.uploaded, dbQueue: sqlCapturingQueue)
        let capturedSQL = sqlCapturingQueue.lastCapturedSQL!
        let capturedValues = sqlCapturingQueue.capturedQueries.last?.values

        // Build the equivalent GRDB query
        let grdbRequest = UserEpisodeRecord
            .filter(UserEpisodeRecord.Columns.uploadStatus == UploadStatus.uploaded.rawValue)
        let grdbSQL = try extractSQL(grdbRequest)

        // GRDB parameterizes uploadStatus
        let grdbValues: [Any] = [UploadStatus.uploaded.rawValue]

        // Compare the SQL
        assertSQLEquivalent(capturedSQL, grdbSQL)
    }

    // MARK: - Unsynced Episodes Query Tests

    func testUnsyncedEpisodesQuery() throws {
        // Call the SQL implementation to capture the query
        _ = userEpisodeDataManager.unsyncedEpisodes(dbQueue: sqlCapturingQueue)
        let capturedSQL = sqlCapturingQueue.lastCapturedSQL!
        let capturedValues = sqlCapturingQueue.capturedQueries.last?.values

        // Build the equivalent GRDB query
        let titleModFilter = UserEpisodeRecord.Columns.titleModified > 0
        let imageColorModFilter = UserEpisodeRecord.Columns.imageColorModified > 0
        let playingStatusModFilter = UserEpisodeRecord.Columns.playingStatusModified > 0
        let playedUpToModFilter = UserEpisodeRecord.Columns.playedUpToModified > 0
        let durationModFilter = UserEpisodeRecord.Columns.durationModified > 0
        let combinedFilter = titleModFilter || imageColorModFilter || playingStatusModFilter || playedUpToModFilter || durationModFilter

        let grdbRequest = UserEpisodeRecord
            .filter(combinedFilter)
        let grdbSQL = try extractSQL(grdbRequest)

        // GRDB parameterizes the > 0 comparisons
        let grdbValues: [Any] = [0, 0, 0, 0, 0]

        // Compare the SQL
        assertSQLEquivalent(capturedSQL, grdbSQL)
    }

    // MARK: - Downloaded Episode Count Query Tests

    func testDownloadedEpisodeCountQuery() throws {
        // Call the SQL implementation to capture the query
        _ = userEpisodeDataManager.downloadedEpisodeCount(dbQueue: sqlCapturingQueue)
        let capturedSQL = sqlCapturingQueue.lastCapturedSQL!
        let capturedValues = sqlCapturingQueue.capturedQueries.last?.values

        // Build the equivalent GRDB query
        let grdbRequest = UserEpisodeRecord
            .filter(UserEpisodeRecord.Columns.episodeStatus == DownloadStatus.downloaded.rawValue)
        let grdbSQL = try extractCountSQL(grdbRequest)

        // GRDB parameterizes episodeStatus
        let grdbValues: [Any] = [DownloadStatus.downloaded.rawValue]

        // Compare the SQL
        assertSQLEquivalent(capturedSQL, grdbSQL)
    }

    // MARK: - Remove Orphaned Query Tests

    func testRemoveOrphanedQuery() throws {
        // Call the SQL implementation to capture the query
        userEpisodeDataManager.removeOrphaned(dbQueue: sqlCapturingQueue)
        let capturedSQL = sqlCapturingQueue.lastCapturedSQL!

        // Build the equivalent GRDB query
        let grdbRequest = UserEpisodeRecord
            .filter(UserEpisodeRecord.Columns.uploadStatus == UploadStatus.notUploaded.rawValue)
            .filter(
                UserEpisodeRecord.Columns.episodeStatus == DownloadStatus.notDownloaded.rawValue ||
                UserEpisodeRecord.Columns.episodeStatus == DownloadStatus.downloadFailed.rawValue
            )
        let grdbSQL = try extractDeleteSQL(grdbRequest)

        // GRDB parameterizes the values
        let grdbValues: [Any] = [UploadStatus.notUploaded.rawValue, DownloadStatus.notDownloaded.rawValue, DownloadStatus.downloadFailed.rawValue]

        // Compare the SQL
        assertSQLEquivalent(capturedSQL, grdbSQL)
    }

    // MARK: - Delete Query Tests

    func testDeleteByUuidQuery() throws {
        // Call the SQL implementation to capture the query
        userEpisodeDataManager.delete(userEpisodeUuid: "test-uuid", dbQueue: sqlCapturingQueue)
        let capturedSQL = sqlCapturingQueue.lastCapturedSQL!

        // Build the equivalent GRDB query
        let grdbRequest = UserEpisodeRecord
            .filter(UserEpisodeRecord.Columns.uuid == "test-uuid")
        let grdbSQL = try extractDeleteSQL(grdbRequest)

        // Compare the SQL
        assertSQLEquivalent(capturedSQL, grdbSQL)
    }

    func testDeleteByMultipleUuidsQuery() throws {
        let uuids = ["uuid-1", "uuid-2", "uuid-3"]

        // Call the SQL implementation to capture the query
        userEpisodeDataManager.delete(userEpisodeUuids: uuids, dbQueue: sqlCapturingQueue)
        let capturedSQL = sqlCapturingQueue.lastCapturedSQL!

        // Build the equivalent GRDB query
        let grdbRequest = UserEpisodeRecord
            .filter(uuids.contains(UserEpisodeRecord.Columns.uuid))
        let grdbSQL = try extractDeleteSQL(grdbRequest)

        // Compare the SQL
        assertSQLEquivalent(capturedSQL, grdbSQL)
    }
}
