# Nodes with values to reuse in the pipeline.
common_params:
  # Common plugin settings to use with the `plugins` key.
  - &common_plugins
    - automattic/bash-cache#2.6.0
    - automattic/git-s3-cache#v1.1.2:
        bucket: a8c-repo-mirrors
        # This is not the name of the repo but the key used in the bucket,
        # which is set based on the Buildkite pipeline slug
        repo: wordpress-mobile/pocket-casts-ios/
  # Common environment values to use with the `env` key.
  - &common_env
    IMAGE_ID: xcode-13.4.1
  # Common agents values to use with the `agents` key.
  - &common_agents
    queue: mac
    dc_location: mke

steps:
  - label: Build and Test
    command: .buildkite/commands/build.sh
    agents: *common_agents
    env: *common_env
    plugins: *common_plugins

  - label: Lints via Danger
    command: .buildkite/commands/danger.sh
    agents: *common_agents
    env: *common_env
    plugins: *common_plugins
