# Nodes with values to reuse in the pipeline.
common_params:
  # Common plugin settings to use with the `plugins` key.
  - &common_plugins
    - automattic/a8c-ci-toolkit#2.15.1
    - automattic/git-s3-cache#1.1.4:
        bucket: a8c-repo-mirrors
        repo: automattic/pocket-casts-ios/
  # Common environment values to use with the `env` key.
  - &common_env
    # If you update the image to a newer Xcode version, don't forget to also update the badge in the README.md file accordingly for consistency
    IMAGE_ID: xcode-15.0
  # Common agents values to use with the `agents` key.
  - &common_agents
    queue: mac

steps:
  - label: Build and Test
    command: .buildkite/commands/build.sh
    agents: *common_agents
    env: *common_env
    plugins: *common_plugins

  - group: Linters
    steps:
      - label: Lints via Danger
        command: .buildkite/commands/danger.sh
        agents: *common_agents
        env: *common_env
        plugins: *common_plugins

      - label: ":sleuth_or_spy: Lint Localized Strings Format"
        command: lint_localized_strings_format
        plugins: *common_plugins
        env: *common_env
