# Nodes with values to reuse in the pipeline.
common_params:
  # Common plugin settings to use with the `plugins` key.
  - &common_plugins
    - automattic/bash-cache#2.8.0
    - automattic/git-s3-cache#v1.1.3:
        bucket: a8c-repo-mirrors
        repo: automattic/pocket-casts-ios/
  # Common environment values to use with the `env` key.
  - &common_env
    # If you update the image to a newer Xcode version, don't forget to also update the badge in the README.md file accordingly for consistency
    IMAGE_ID: xcode-14
  # Common agents values to use with the `agents` key.
  - &common_agents
    queue: mac

steps:
  - label: ":cocoapods: Rebuild CocoaPods cache"
    command: |
      echo "--- :rubygems: Setting up Gems"
      install_gems

      echo "--- :cocoapods: Rebuilding CocoaPods Cache"
      cache_cocoapods_specs_repos
    plugins: *common_plugins
    agents:
      queue: mac
    env:
      IMAGE_ID: xcode-14

  - label: ":git: Rebuild git cache"
    command: cache_repo a8c-repo-mirrors
    plugins: *common_plugins
    agents:
      queue: default

  - label: "🛠 Release Build (App Store Connect)"
    command: ".buildkite/commands/release-build.sh $BETA_RELEASE"
    env: *common_env
    plugins: *common_plugins
    notify:
    - slack: "#build-and-ship"
