# This pipeline is meant to be run via the Buildkite API, and is only used for release builds

# Nodes with values to reuse in the pipeline.
common_params:
  # Common plugin settings to use with the `plugins` key.
  - &common_plugins
    - automattic/bash-cache#v1.6.1
    - automattic/git-s3-cache#v1.1.0:
        bucket: "a8c-repo-mirrors"
        repo: "automattic/pocket-casts-ios/"
  # Common environment values to use with the `env` key.
  - &common_env
    IMAGE_ID: xcode-13.4.1

steps:

  - label: "🛠 Release Build (App Store Connect)"
    command: ".buildkite/commands/release-build.sh $BETA_RELEASE"
    env: *common_env
    plugins: *common_plugins
    notify:
    - slack: "#build-and-ship"
