#!/bin/bash

# This file is `source`'d before calling `buildkite-agent pipeline upload`, and can be used
# to set up some variables that will be interpolated in the `.yml` pipeline before uploading it.

# 🎗️ If you update the image to a newer Xcode version, don't forget to also update the badge in the README.md file accordingly for consistency
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

XCODE_VERSION_FILE="$SCRIPT_DIR/../.xcode-version"
if [[ ! -s "$XCODE_VERSION_FILE" ]]; then
    echo "Error: '$XCODE_VERSION_FILE' not found or empty." >&2
    exit 1
fi
XCODE_VERSION=$(sed -E 's/^~> ?//' "$XCODE_VERSION_FILE")

CI_TOOLKIT_PLUGIN_VERSION="6.0.0"

TEST_COLLECTOR_PLUGIN_VERSION="1.11.0"

export IMAGE_ID="xcode-$XCODE_VERSION"
export CI_TOOLKIT="automattic/a8c-ci-toolkit#$CI_TOOLKIT_PLUGIN_VERSION"
export TEST_COLLECTOR="test-collector#v$TEST_COLLECTOR_PLUGIN_VERSION"
