#!/bin/sh

# This file is `source`'d before calling `buildkite-agent pipeline upload`, and can be used
# to set up some variables that will be interpolated in the `.yml` pipeline before uploading it.

# 🎗️ If you update the image to a newer Xcode version, don't forget to also update the badge in the README.md file accordingly for consistency
XCODE_VERSION="16.1"
CI_TOOLKIT_PLUGIN_VERSION="3.7.1"

# Note: `-v4` suffix added to use xcode-16.1-v4 image; remember to remove that suffix on next Xcode update
export IMAGE_ID="xcode-$XCODE_VERSION-v4"
export CI_TOOLKIT="automattic/a8c-ci-toolkit#$CI_TOOLKIT_PLUGIN_VERSION"
