# frozen_string_literal: true

return if github.pr_labels.include?('Releases')

manifest_pr_checker.check_all_manifest_lock_updated
labels_checker.check(
  required_labels: [//],
  required_labels_error: 'PR is missing at least one label.'
)
view_changes_need_screenshots.view_changes_need_screenshots
pr_size_checker.check_diff_size
milestone_checker.check_milestone_due_date(days_before_due: 2)

github.dismiss_out_of_range_messages
rubocop.lint inline_comment: true, fail_on_inline_comment: true, include_cop_names: true

swiftlint.binary_path = './Pods/SwiftLint/swiftlint'
swiftlint.lint_all_files = true
swiftlint.lint_files

warn('PR is classed as Work in Progress') if github.pr_title.include? '[WIP]'

warn("No reviewers have been set for this PR yet. Please request a review from **@\u2028Automattic/pocket-casts-ios**.") unless github.pr_json['assignee']
